root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/zglowmlljets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/zglowmlljets.root\",\"/eos/user/a/aejung/andrew/data/nano/zglowmlljets/2016/zglowmlljets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/zglowmlljets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/zglowmlljets.root\",\"/eos/user/a/aejung/andrew/data/nano/zglowmlljets/2017/zglowmlljets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/zglowmlljets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/zglowmlljets.root\",\"/eos/user/a/aejung/andrew/data/nano/zglowmlljets/2018/zglowmlljets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/wgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/wgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wgjets/2016/wgjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/wgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/wgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wgjets/2017/wgjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/wgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/wgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wgjets/2018/wgjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/wwjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/wwjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wwjets/2016/wwjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/wwjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/wwjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wwjets/2017/wwjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/wwjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/wwjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wwjets/2018/wwjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/wzjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/wzjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wzjets/2016/wzjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/wzjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/wzjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wzjets/2017/wzjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/wzjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/wzjets.root\",\"/eos/user/a/aejung/andrew/data/nano/wzjets/2018/wzjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/zzjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/zzjets.root\",\"/eos/user/a/aejung/andrew/data/nano/zzjets/2016/zzjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/zzjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/zzjets.root\",\"/eos/user/a/aejung/andrew/data/nano/zzjets/2017/zzjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/zzjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/zzjets.root\",\"/eos/user/a/aejung/andrew/data/nano/zzjets/2018/zzjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/tgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/tgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/tgjets/2016/tgjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/tgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/tgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/tgjets/2017/tgjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/tgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/tgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/tgjets/2018/tgjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/zjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/zjets.root\",\"/eos/user/a/aejung/andrew/data/nano/zjets/2016/zjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/zjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/zjets.root\",\"/eos/user/a/aejung/andrew/data/nano/zjets/2017/zjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/zjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/zjets.root\",\"/eos/user/a/aejung/andrew/data/nano/zjets/2018/zjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/stschanneljets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/stschanneljets.root\",\"/eos/user/a/aejung/andrew/data/nano/stschanneljets/2016/stschanneljets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/stschanneljets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/stschanneljets.root\",\"/eos/user/a/aejung/andrew/data/nano/stschanneljets/2017/stschanneljets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/stschanneljets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/stschanneljets.root\",\"/eos/user/a/aejung/andrew/data/nano/stschanneljets/2018/stschanneljets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/sttchanneltopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/sttchanneltopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttchanneltopjets/2016/sttchanneltopjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/sttchanneltopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/sttchanneltopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttchanneltopjets/2017/sttchanneltopjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/sttchanneltopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/sttchanneltopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttchanneltopjets/2018/sttchanneltopjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/sttchannelantitopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/sttchannelantitopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttchannelantitopjets/2016/sttchannelantitopjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/sttchannelantitopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/sttchannelantitopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttchannelantitopjets/2017/sttchannelantitopjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/sttchannelantitopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/sttchannelantitopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttchannelantitopjets/2018/sttchannelantitopjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/sttwtopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/sttwtopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttwtopjets/2016/sttwtopjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/sttwtopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/sttwtopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttwtopjets/2017/sttwtopjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/sttwtopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/sttwtopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttwtopjets/2018/sttwtopjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/sttwantitopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/sttwantitopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttwantitopjets/2016/sttwantitopjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/sttwantitopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/sttwantitopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttwantitopjets/2017/sttwantitopjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/sttwantitopjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/sttwantitopjets.root\",\"/eos/user/a/aejung/andrew/data/nano/sttwantitopjets/2018/sttwantitopjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/ttgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/ttgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttgjets/2016/ttgjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/ttgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/ttgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttgjets/2017/ttgjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/ttgjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/ttgjets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttgjets/2018/ttgjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/ttwjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/ttwjets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttwjets/2016/ttwjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/ttwjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/ttwjets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttwjets/2017/ttwjets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/ttwjets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/ttwjets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttwjets/2018/ttwjets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/tt2l2nujets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/tt2l2nujets.root\",\"/eos/user/a/aejung/andrew/data/nano/tt2l2nujets/2016/tt2l2nujets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/tt2l2nujets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/tt2l2nujets.root\",\"/eos/user/a/aejung/andrew/data/nano/tt2l2nujets/2017/tt2l2nujets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/tt2l2nujets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/tt2l2nujets.root\",\"/eos/user/a/aejung/andrew/data/nano/tt2l2nujets/2018/tt2l2nujets.*.root\"\)

root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019/ttsemijets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2016/1June2019jetunc/ttsemijets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttsemijets/2016/ttsemijets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019/ttsemijets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2017/1June2019jetunc/ttsemijets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttsemijets/2017/ttsemijets.*.root\"\)
root -l -b -q add_puppimet_uncertainties.C+\(\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019/ttsemijets.root\",\"/afs/cern.ch/work/a/amlevin/data/wg/2018/1June2019jetunc/ttsemijets.root\",\"/eos/user/a/aejung/andrew/data/nano/ttsemijets/2018/ttsemijets.*.root\"\)
