cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/real_photon_template_20to30.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/fake_photon_template_20to30.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/fit_20to30.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/components_20to30.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/real_photon_template_30to40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/fake_photon_template_30to40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/fit_30to40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/components_30to40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/real_photon_template_40to50.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/fake_photon_template_40to50.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/fit_40to50.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/components_40to50.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/real_photon_template_50to400.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/fake_photon_template_50to400.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/fit_50to400.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/barrel/components_50to400.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/barrel/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/real_photon_template_20to30.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/fake_photon_template_20to30.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/fit_20to30.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/components_20to30.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/real_photon_template_30to40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/fake_photon_template_30to40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/fit_30to40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/components_30to40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/real_photon_template_40to50.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/fake_photon_template_40to50.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/fit_40to50.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/components_40to50.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/real_photon_template_50to400.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/fake_photon_template_50to400.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/fit_50to400.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/
cp /eos/user/a/amlevin/www/wg/fake-photon-fits/2016/both/endcap/components_50to400.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/endcap/

cp /eos/user/a/amlevin/www/wg/muon/njets40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/
cp /eos/user/a/amlevin/www/wg/muon/drlg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/
cp /eos/user/a/amlevin/www/wg/muon/puppimt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/mt.png          
cp /eos/user/a/amlevin/www/wg/muon/puppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/met.png
cp /eos/user/a/amlevin/www/wg/muon/puppimetphi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/metphi.png
cp /eos/user/a/amlevin/www/wg/muon/dphilg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/
cp /eos/user/a/amlevin/www/wg/muon/detalg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/
cp /eos/user/a/amlevin/www/wg/muon/dphilpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/dphilmet.png          
cp /eos/user/a/amlevin/www/wg/muon/dphigpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/dphigmet.png          
cp /eos/user/a/amlevin/www/wg/muon/mlg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/          
cp /eos/user/a/amlevin/www/wg/muon/lepton_pt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/   
cp /eos/user/a/amlevin/www/wg/muon/lepton_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/   
cp /eos/user/a/amlevin/www/wg/muon/lepton_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/   
cp /eos/user/a/amlevin/www/wg/muon/photon_pt_20to180.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/photon_pt.png
cp /eos/user/a/amlevin/www/wg/muon/photon_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/
cp /eos/user/a/amlevin/www/wg/muon/photon_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/muon/

cp /eos/user/a/amlevin/www/wg-zveto/electron/njets40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/
cp /eos/user/a/amlevin/www/wg-zveto/electron/drlg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/
cp /eos/user/a/amlevin/www/wg-zveto/electron/puppimt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/mt.png          
cp /eos/user/a/amlevin/www/wg-zveto/electron/puppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/met.png
cp /eos/user/a/amlevin/www/wg-zveto/electron/puppimetphi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/metphi.png
cp /eos/user/a/amlevin/www/wg-zveto/electron/dphilg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/
cp /eos/user/a/amlevin/www/wg-zveto/electron/detalg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/
cp /eos/user/a/amlevin/www/wg-zveto/electron/dphilpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/dphilmet.png          
cp /eos/user/a/amlevin/www/wg-zveto/electron/dphigpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/dphigmet.png          
cp /eos/user/a/amlevin/www/wg-zveto/electron/mlg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/          
cp /eos/user/a/amlevin/www/wg-zveto/electron/lepton_pt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/   
cp /eos/user/a/amlevin/www/wg-zveto/electron/lepton_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/   
cp /eos/user/a/amlevin/www/wg-zveto/electron/lepton_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/   
cp /eos/user/a/amlevin/www/wg-zveto/electron/photon_pt_20to180.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/photon_pt.png
cp /eos/user/a/amlevin/www/wg-zveto/electron/photon_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/
cp /eos/user/a/amlevin/www/wg-zveto/electron/photon_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/

cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/njets40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/drlg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/puppimt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/mt.png          
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/puppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/met.png
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/puppimetphi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/metphi.png
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/dphilg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/detalg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/dphilpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/dphilmet.png          
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/dphigpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/dphigmet.png          
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/mlg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/          
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/lepton_pt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/   
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/lepton_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/   
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/lepton_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/   
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/photon_pt_20to180.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/photon_pt.png
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/photon_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/
cp /eos/user/a/amlevin/www/wg-mcfakephoton/muon/photon_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/muon/

cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/njets40.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/drlg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/puppimt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/mt.png          
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/puppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/met.png
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/puppimetphi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/metphi.png
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/dphilg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/detalg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/dphilpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/dphilmet.png
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/dphigpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/dphigmet.png
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/mlg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/          
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/lepton_pt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/   
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/lepton_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/   
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/lepton_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/   
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/photon_pt_20to180.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/photon_pt.png
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/photon_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/
cp /eos/user/a/amlevin/www/wg-zveto-mcfakephoton/electron/photon_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/mcfakephoton/electron/

cp /eos/user/a/amlevin/www/wg/scaling_cpwww_bin[1234].png  /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/
cp /eos/user/a/amlevin/www/wg/scaling_cpw_bin[1234].png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/ 
cp /eos/user/a/amlevin/www/wg/scaling_cwww_bin[1234].png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/
cp /eos/user/a/amlevin/www/wg/scaling_cw_bin[1234].png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/
cp /eos/user/a/amlevin/www/wg/scaling_cb_bin[1234].png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/

cp /eos/user/a/amlevin/www/wg/deltaNLL.cpw.expected.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/deltaNLL_cpw_expected.png
cp /eos/user/a/amlevin/www/wg/deltaNLL.cpwww.expected.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/deltaNLL_cpwww_expected.png
cp /eos/user/a/amlevin/www/wg/deltaNLL.cb.expected.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/deltaNLL_cb_expected.png
cp /eos/user/a/amlevin/www/wg/deltaNLL.cwww.expected.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/deltaNLL_cwww_expected.png
cp /eos/user/a/amlevin/www/wg/deltaNLL.cw.expected.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/ewdim6/deltaNLL_cw_expected.png

cp /eos/user/a/amlevin/www/wg/electron/frame2.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/fitresult1.png
cp /eos/user/a/amlevin/www/wg/electron/frame4.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/fitresult2.png

cp /eos/user/a/amlevin/www/wg/fake-photon/sources/dphilg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/sources/
cp /eos/user/a/amlevin/www/wg/fake-photon/sources/dphilpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/sources/dphilmet.png
cp /eos/user/a/amlevin/www/wg/fake-photon/sources/photon_pt_20to180.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/sources/photon_pt.png
cp /eos/user/a/amlevin/www/wg/fake-photon/sources/lepton_pt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/sources/
cp /eos/user/a/amlevin/www/wg/fake-photon/sources/met.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/sources/
cp /eos/user/a/amlevin/www/wg/fake-photon/sources/mt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/sources/

cp /eos/user/a/amlevin/www/wg/fake-photon/closure/photon_pt_20to180.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/closure/photon_pt.png
cp /eos/user/a/amlevin/www/wg/fake-photon/closure/photon_eta.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/closure/
cp /eos/user/a/amlevin/www/wg/fake-photon/closure/photon_phi.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/closure/
cp /eos/user/a/amlevin/www/wg/fake-photon/closure/puppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/closure/met.png
cp /eos/user/a/amlevin/www/wg/fake-photon/closure/dphilg.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/closure/
cp /eos/user/a/amlevin/www/wg/fake-photon/closure/dphilpuppimet.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/fake-photon/closure/dphilmet.png

cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/eff_data_2016_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/
cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/eff_data_2017_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/
cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/eff_data_2018_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/
cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/eff_mc_2016_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/
cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/eff_mc_2017_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/
cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/eff_mc_2018_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/
cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/sf_2016_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/
cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/sf_2017_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/
cp /eos/user/a/amlevin/www/wg/electron-hlt-sfs/sf_2018_etapt.png /afs/cern.ch/user/a/amlevin/tdr/notes/AN-18-238/plots/electron/hltsfs/

