import ROOT
ROOT.PyConfig.IgnoreCommandLineOptions = True

from PhysicsTools.NanoAODTools.postprocessing.framework.datamodel import Collection
from PhysicsTools.NanoAODTools.postprocessing.framework.eventloop import Module

from PhysicsTools.NanoAODTools.postprocessing.tools import deltaR

class countHistogramsFiducialProducer(Module):
    def __init__(self):
        pass
    def beginJob(self):
        pass
    def endJob(self):
        pass
    def beginFile(self, inputFile, outputFile, inputTree, wrappedOutputTree):
        self.h_nweightedeventspassfidselection=ROOT.TH1D('nEventsGenWeighted_PassFidSelection',   'nEventsGenWeighted_PassFidSelection',   1, 0, 1)
        self.h_nweightedeventspassfidselection_qcdscaleweight0=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_QCDScaleWeight0',   'nEventsGenWeighted_PassFidSelection_QCDScaleWeight0',   1, 0, 1)
        self.h_nweightedeventspassfidselection_qcdscaleweight1=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_QCDScaleWeight1',   'nEventsGenWeighted_PassFidSelection_QCDScaleWeight1',   1, 0, 1)
        self.h_nweightedeventspassfidselection_qcdscaleweight2=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_QCDScaleWeight2',   'nEventsGenWeighted_PassFidSelection_QCDScaleWeight2',   1, 0, 1)
        self.h_nweightedeventspassfidselection_qcdscaleweight3=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_QCDScaleWeight3',   'nEventsGenWeighted_PassFidSelection_QCDScaleWeight3',   1, 0, 1)
        self.h_nweightedeventspassfidselection_qcdscaleweight4=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_QCDScaleWeight4',   'nEventsGenWeighted_PassFidSelection_QCDScaleWeight4',   1, 0, 1)
        self.h_nweightedeventspassfidselection_qcdscaleweight5=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_QCDScaleWeight5',   'nEventsGenWeighted_PassFidSelection_QCDScaleWeight5',   1, 0, 1)
        self.h_nweightedeventspassfidselection_qcdscaleweight6=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_QCDScaleWeight6',   'nEventsGenWeighted_PassFidSelection_QCDScaleWeight6',   1, 0, 1)
        self.h_nweightedeventspassfidselection_qcdscaleweight7=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_QCDScaleWeight7',   'nEventsGenWeighted_PassFidSelection_QCDScaleWeight7',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight1=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight1',   'nEventsGenWeighted_PassFidSelection_PDFWeight1',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight2=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight2',   'nEventsGenWeighted_PassFidSelection_PDFWeight2',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight3=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight3',   'nEventsGenWeighted_PassFidSelection_PDFWeight3',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight4=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight4',   'nEventsGenWeighted_PassFidSelection_PDFWeight4',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight5=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight5',   'nEventsGenWeighted_PassFidSelection_PDFWeight5',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight6=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight6',   'nEventsGenWeighted_PassFidSelection_PDFWeight6',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight7=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight7',   'nEventsGenWeighted_PassFidSelection_PDFWeight7',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight8=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight8',   'nEventsGenWeighted_PassFidSelection_PDFWeight8',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight9=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight9',   'nEventsGenWeighted_PassFidSelection_PDFWeight9',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight10=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight10',   'nEventsGenWeighted_PassFidSelection_PDFWeight10',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight11=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight11',   'nEventsGenWeighted_PassFidSelection_PDFWeight11',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight12=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight12',   'nEventsGenWeighted_PassFidSelection_PDFWeight12',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight13=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight13',   'nEventsGenWeighted_PassFidSelection_PDFWeight13',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight14=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight14',   'nEventsGenWeighted_PassFidSelection_PDFWeight14',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight15=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight15',   'nEventsGenWeighted_PassFidSelection_PDFWeight15',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight16=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight16',   'nEventsGenWeighted_PassFidSelection_PDFWeight16',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight17=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight17',   'nEventsGenWeighted_PassFidSelection_PDFWeight17',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight18=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight18',   'nEventsGenWeighted_PassFidSelection_PDFWeight18',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight19=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight19',   'nEventsGenWeighted_PassFidSelection_PDFWeight19',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight20=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight20',   'nEventsGenWeighted_PassFidSelection_PDFWeight20',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight21=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight21',   'nEventsGenWeighted_PassFidSelection_PDFWeight21',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight22=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight22',   'nEventsGenWeighted_PassFidSelection_PDFWeight22',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight23=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight23',   'nEventsGenWeighted_PassFidSelection_PDFWeight23',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight24=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight24',   'nEventsGenWeighted_PassFidSelection_PDFWeight24',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight25=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight25',   'nEventsGenWeighted_PassFidSelection_PDFWeight25',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight26=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight26',   'nEventsGenWeighted_PassFidSelection_PDFWeight26',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight27=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight27',   'nEventsGenWeighted_PassFidSelection_PDFWeight27',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight28=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight28',   'nEventsGenWeighted_PassFidSelection_PDFWeight28',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight29=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight29',   'nEventsGenWeighted_PassFidSelection_PDFWeight29',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight30=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight30',   'nEventsGenWeighted_PassFidSelection_PDFWeight30',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight31=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight31',   'nEventsGenWeighted_PassFidSelection_PDFWeight31',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight32=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight32',   'nEventsGenWeighted_PassFidSelection_PDFWeight32',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight33=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight33',   'nEventsGenWeighted_PassFidSelection_PDFWeight33',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight34=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight34',   'nEventsGenWeighted_PassFidSelection_PDFWeight34',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight35=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight35',   'nEventsGenWeighted_PassFidSelection_PDFWeight35',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight36=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight36',   'nEventsGenWeighted_PassFidSelection_PDFWeight36',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight37=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight37',   'nEventsGenWeighted_PassFidSelection_PDFWeight37',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight38=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight38',   'nEventsGenWeighted_PassFidSelection_PDFWeight38',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight39=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight39',   'nEventsGenWeighted_PassFidSelection_PDFWeight39',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight40=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight40',   'nEventsGenWeighted_PassFidSelection_PDFWeight40',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight41=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight41',   'nEventsGenWeighted_PassFidSelection_PDFWeight41',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight42=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight42',   'nEventsGenWeighted_PassFidSelection_PDFWeight42',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight43=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight43',   'nEventsGenWeighted_PassFidSelection_PDFWeight43',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight44=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight44',   'nEventsGenWeighted_PassFidSelection_PDFWeight44',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight45=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight45',   'nEventsGenWeighted_PassFidSelection_PDFWeight45',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight46=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight46',   'nEventsGenWeighted_PassFidSelection_PDFWeight46',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight47=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight47',   'nEventsGenWeighted_PassFidSelection_PDFWeight47',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight48=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight48',   'nEventsGenWeighted_PassFidSelection_PDFWeight48',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight49=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight49',   'nEventsGenWeighted_PassFidSelection_PDFWeight49',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight50=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight50',   'nEventsGenWeighted_PassFidSelection_PDFWeight50',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight51=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight51',   'nEventsGenWeighted_PassFidSelection_PDFWeight51',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight52=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight52',   'nEventsGenWeighted_PassFidSelection_PDFWeight52',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight53=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight53',   'nEventsGenWeighted_PassFidSelection_PDFWeight53',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight54=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight54',   'nEventsGenWeighted_PassFidSelection_PDFWeight54',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight55=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight55',   'nEventsGenWeighted_PassFidSelection_PDFWeight55',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight56=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight56',   'nEventsGenWeighted_PassFidSelection_PDFWeight56',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight57=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight57',   'nEventsGenWeighted_PassFidSelection_PDFWeight57',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight58=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight58',   'nEventsGenWeighted_PassFidSelection_PDFWeight58',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight59=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight59',   'nEventsGenWeighted_PassFidSelection_PDFWeight59',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight60=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight60',   'nEventsGenWeighted_PassFidSelection_PDFWeight60',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight61=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight61',   'nEventsGenWeighted_PassFidSelection_PDFWeight61',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight62=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight62',   'nEventsGenWeighted_PassFidSelection_PDFWeight62',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight63=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight63',   'nEventsGenWeighted_PassFidSelection_PDFWeight63',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight64=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight64',   'nEventsGenWeighted_PassFidSelection_PDFWeight64',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight65=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight65',   'nEventsGenWeighted_PassFidSelection_PDFWeight65',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight66=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight66',   'nEventsGenWeighted_PassFidSelection_PDFWeight66',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight67=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight67',   'nEventsGenWeighted_PassFidSelection_PDFWeight67',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight68=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight68',   'nEventsGenWeighted_PassFidSelection_PDFWeight68',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight69=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight69',   'nEventsGenWeighted_PassFidSelection_PDFWeight69',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight70=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight70',   'nEventsGenWeighted_PassFidSelection_PDFWeight70',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight71=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight71',   'nEventsGenWeighted_PassFidSelection_PDFWeight71',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight72=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight72',   'nEventsGenWeighted_PassFidSelection_PDFWeight72',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight73=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight73',   'nEventsGenWeighted_PassFidSelection_PDFWeight73',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight74=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight74',   'nEventsGenWeighted_PassFidSelection_PDFWeight74',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight75=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight75',   'nEventsGenWeighted_PassFidSelection_PDFWeight75',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight76=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight76',   'nEventsGenWeighted_PassFidSelection_PDFWeight76',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight77=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight77',   'nEventsGenWeighted_PassFidSelection_PDFWeight77',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight78=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight78',   'nEventsGenWeighted_PassFidSelection_PDFWeight78',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight79=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight79',   'nEventsGenWeighted_PassFidSelection_PDFWeight79',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight80=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight80',   'nEventsGenWeighted_PassFidSelection_PDFWeight80',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight81=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight81',   'nEventsGenWeighted_PassFidSelection_PDFWeight81',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight82=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight82',   'nEventsGenWeighted_PassFidSelection_PDFWeight82',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight83=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight83',   'nEventsGenWeighted_PassFidSelection_PDFWeight83',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight84=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight84',   'nEventsGenWeighted_PassFidSelection_PDFWeight84',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight85=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight85',   'nEventsGenWeighted_PassFidSelection_PDFWeight85',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight86=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight86',   'nEventsGenWeighted_PassFidSelection_PDFWeight86',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight87=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight87',   'nEventsGenWeighted_PassFidSelection_PDFWeight87',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight88=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight88',   'nEventsGenWeighted_PassFidSelection_PDFWeight88',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight89=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight89',   'nEventsGenWeighted_PassFidSelection_PDFWeight89',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight90=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight90',   'nEventsGenWeighted_PassFidSelection_PDFWeight90',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight91=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight91',   'nEventsGenWeighted_PassFidSelection_PDFWeight91',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight92=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight92',   'nEventsGenWeighted_PassFidSelection_PDFWeight92',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight93=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight93',   'nEventsGenWeighted_PassFidSelection_PDFWeight93',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight94=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight94',   'nEventsGenWeighted_PassFidSelection_PDFWeight94',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight95=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight95',   'nEventsGenWeighted_PassFidSelection_PDFWeight95',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight96=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight96',   'nEventsGenWeighted_PassFidSelection_PDFWeight96',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight97=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight97',   'nEventsGenWeighted_PassFidSelection_PDFWeight97',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight98=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight98',   'nEventsGenWeighted_PassFidSelection_PDFWeight98',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight99=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight99',   'nEventsGenWeighted_PassFidSelection_PDFWeight99',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight100=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight100',   'nEventsGenWeighted_PassFidSelection_PDFWeight100',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight101=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight101',   'nEventsGenWeighted_PassFidSelection_PDFWeight101',   1, 0, 1)
        self.h_nweightedeventspassfidselection_pdfweight102=ROOT.TH1D('nEventsGenWeighted_PassFidSelection_PDFWeight102',   'nEventsGenWeighted_PassFidSelection_PDFWeight102',   1, 0, 1)


    def endFile(self, inputFile, outputFile, inputTree, wrappedOutputTree):
        prevdir = ROOT.gDirectory
        outputFile.cd()
        self.h_nweightedeventspassfidselection.Write()
        self.h_nweightedeventspassfidselection_qcdscaleweight0.Write()
        self.h_nweightedeventspassfidselection_qcdscaleweight1.Write()
        self.h_nweightedeventspassfidselection_qcdscaleweight2.Write()
        self.h_nweightedeventspassfidselection_qcdscaleweight3.Write()
        self.h_nweightedeventspassfidselection_qcdscaleweight4.Write()
        self.h_nweightedeventspassfidselection_qcdscaleweight5.Write()
        self.h_nweightedeventspassfidselection_qcdscaleweight6.Write()
        self.h_nweightedeventspassfidselection_qcdscaleweight7.Write()
        self.h_nweightedeventspassfidselection_pdfweight1.Write()
        self.h_nweightedeventspassfidselection_pdfweight2.Write()
        self.h_nweightedeventspassfidselection_pdfweight3.Write()
        self.h_nweightedeventspassfidselection_pdfweight4.Write()
        self.h_nweightedeventspassfidselection_pdfweight5.Write()
        self.h_nweightedeventspassfidselection_pdfweight6.Write()
        self.h_nweightedeventspassfidselection_pdfweight7.Write()
        self.h_nweightedeventspassfidselection_pdfweight8.Write()
        self.h_nweightedeventspassfidselection_pdfweight9.Write()
        self.h_nweightedeventspassfidselection_pdfweight10.Write()
        self.h_nweightedeventspassfidselection_pdfweight11.Write()
        self.h_nweightedeventspassfidselection_pdfweight12.Write()
        self.h_nweightedeventspassfidselection_pdfweight13.Write()
        self.h_nweightedeventspassfidselection_pdfweight14.Write()
        self.h_nweightedeventspassfidselection_pdfweight15.Write()
        self.h_nweightedeventspassfidselection_pdfweight16.Write()
        self.h_nweightedeventspassfidselection_pdfweight17.Write()
        self.h_nweightedeventspassfidselection_pdfweight18.Write()
        self.h_nweightedeventspassfidselection_pdfweight19.Write()
        self.h_nweightedeventspassfidselection_pdfweight20.Write()
        self.h_nweightedeventspassfidselection_pdfweight21.Write()
        self.h_nweightedeventspassfidselection_pdfweight22.Write()
        self.h_nweightedeventspassfidselection_pdfweight23.Write()
        self.h_nweightedeventspassfidselection_pdfweight24.Write()
        self.h_nweightedeventspassfidselection_pdfweight25.Write()
        self.h_nweightedeventspassfidselection_pdfweight26.Write()
        self.h_nweightedeventspassfidselection_pdfweight27.Write()
        self.h_nweightedeventspassfidselection_pdfweight28.Write()
        self.h_nweightedeventspassfidselection_pdfweight29.Write()
        self.h_nweightedeventspassfidselection_pdfweight30.Write()
        self.h_nweightedeventspassfidselection_pdfweight31.Write()
        self.h_nweightedeventspassfidselection_pdfweight32.Write()
        self.h_nweightedeventspassfidselection_pdfweight33.Write()
        self.h_nweightedeventspassfidselection_pdfweight34.Write()
        self.h_nweightedeventspassfidselection_pdfweight35.Write()
        self.h_nweightedeventspassfidselection_pdfweight36.Write()
        self.h_nweightedeventspassfidselection_pdfweight37.Write()
        self.h_nweightedeventspassfidselection_pdfweight38.Write()
        self.h_nweightedeventspassfidselection_pdfweight39.Write()
        self.h_nweightedeventspassfidselection_pdfweight40.Write()
        self.h_nweightedeventspassfidselection_pdfweight41.Write()
        self.h_nweightedeventspassfidselection_pdfweight42.Write()
        self.h_nweightedeventspassfidselection_pdfweight43.Write()
        self.h_nweightedeventspassfidselection_pdfweight44.Write()
        self.h_nweightedeventspassfidselection_pdfweight45.Write()
        self.h_nweightedeventspassfidselection_pdfweight46.Write()
        self.h_nweightedeventspassfidselection_pdfweight47.Write()
        self.h_nweightedeventspassfidselection_pdfweight48.Write()
        self.h_nweightedeventspassfidselection_pdfweight49.Write()
        self.h_nweightedeventspassfidselection_pdfweight50.Write()
        self.h_nweightedeventspassfidselection_pdfweight51.Write()
        self.h_nweightedeventspassfidselection_pdfweight52.Write()
        self.h_nweightedeventspassfidselection_pdfweight53.Write()
        self.h_nweightedeventspassfidselection_pdfweight54.Write()
        self.h_nweightedeventspassfidselection_pdfweight55.Write()
        self.h_nweightedeventspassfidselection_pdfweight56.Write()
        self.h_nweightedeventspassfidselection_pdfweight57.Write()
        self.h_nweightedeventspassfidselection_pdfweight58.Write()
        self.h_nweightedeventspassfidselection_pdfweight59.Write()
        self.h_nweightedeventspassfidselection_pdfweight60.Write()
        self.h_nweightedeventspassfidselection_pdfweight61.Write()
        self.h_nweightedeventspassfidselection_pdfweight62.Write()
        self.h_nweightedeventspassfidselection_pdfweight63.Write()
        self.h_nweightedeventspassfidselection_pdfweight64.Write()
        self.h_nweightedeventspassfidselection_pdfweight65.Write()
        self.h_nweightedeventspassfidselection_pdfweight66.Write()
        self.h_nweightedeventspassfidselection_pdfweight67.Write()
        self.h_nweightedeventspassfidselection_pdfweight68.Write()
        self.h_nweightedeventspassfidselection_pdfweight69.Write()
        self.h_nweightedeventspassfidselection_pdfweight70.Write()
        self.h_nweightedeventspassfidselection_pdfweight71.Write()
        self.h_nweightedeventspassfidselection_pdfweight72.Write()
        self.h_nweightedeventspassfidselection_pdfweight73.Write()
        self.h_nweightedeventspassfidselection_pdfweight74.Write()
        self.h_nweightedeventspassfidselection_pdfweight75.Write()
        self.h_nweightedeventspassfidselection_pdfweight76.Write()
        self.h_nweightedeventspassfidselection_pdfweight77.Write()
        self.h_nweightedeventspassfidselection_pdfweight78.Write()
        self.h_nweightedeventspassfidselection_pdfweight79.Write()
        self.h_nweightedeventspassfidselection_pdfweight80.Write()
        self.h_nweightedeventspassfidselection_pdfweight81.Write()
        self.h_nweightedeventspassfidselection_pdfweight82.Write()
        self.h_nweightedeventspassfidselection_pdfweight83.Write()
        self.h_nweightedeventspassfidselection_pdfweight84.Write()
        self.h_nweightedeventspassfidselection_pdfweight85.Write()
        self.h_nweightedeventspassfidselection_pdfweight86.Write()
        self.h_nweightedeventspassfidselection_pdfweight87.Write()
        self.h_nweightedeventspassfidselection_pdfweight88.Write()
        self.h_nweightedeventspassfidselection_pdfweight89.Write()
        self.h_nweightedeventspassfidselection_pdfweight90.Write()
        self.h_nweightedeventspassfidselection_pdfweight91.Write()
        self.h_nweightedeventspassfidselection_pdfweight92.Write()
        self.h_nweightedeventspassfidselection_pdfweight93.Write()
        self.h_nweightedeventspassfidselection_pdfweight94.Write()
        self.h_nweightedeventspassfidselection_pdfweight95.Write()
        self.h_nweightedeventspassfidselection_pdfweight96.Write()
        self.h_nweightedeventspassfidselection_pdfweight97.Write()
        self.h_nweightedeventspassfidselection_pdfweight98.Write()
        self.h_nweightedeventspassfidselection_pdfweight99.Write()
        self.h_nweightedeventspassfidselection_pdfweight100.Write()
        self.h_nweightedeventspassfidselection_pdfweight101.Write()
        self.h_nweightedeventspassfidselection_pdfweight102.Write()
        prevdir.cd()        
    def analyze(self, event):
        if event.pass_fid_selection:    
            if event.Generator_weight > 0:
                self.h_nweightedeventspassfidselection.Fill(0.5)
                self.h_nweightedeventspassfidselection_qcdscaleweight0.Fill(0.5,event.LHEScaleWeight[0])
                self.h_nweightedeventspassfidselection_qcdscaleweight1.Fill(0.5,event.LHEScaleWeight[1])
                self.h_nweightedeventspassfidselection_qcdscaleweight2.Fill(0.5,event.LHEScaleWeight[2])
                self.h_nweightedeventspassfidselection_qcdscaleweight3.Fill(0.5,event.LHEScaleWeight[3])
                self.h_nweightedeventspassfidselection_qcdscaleweight4.Fill(0.5,event.LHEScaleWeight[4])
                self.h_nweightedeventspassfidselection_qcdscaleweight5.Fill(0.5,event.LHEScaleWeight[5])
                self.h_nweightedeventspassfidselection_qcdscaleweight6.Fill(0.5,event.LHEScaleWeight[6])
                self.h_nweightedeventspassfidselection_qcdscaleweight7.Fill(0.5,event.LHEScaleWeight[7])
                self.h_nweightedeventspassfidselection_pdfweight1.Fill(0.5,event.LHEPdfWeight[1])
                self.h_nweightedeventspassfidselection_pdfweight2.Fill(0.5,event.LHEPdfWeight[2])
                self.h_nweightedeventspassfidselection_pdfweight3.Fill(0.5,event.LHEPdfWeight[3])
                self.h_nweightedeventspassfidselection_pdfweight4.Fill(0.5,event.LHEPdfWeight[4])
                self.h_nweightedeventspassfidselection_pdfweight5.Fill(0.5,event.LHEPdfWeight[5])
                self.h_nweightedeventspassfidselection_pdfweight6.Fill(0.5,event.LHEPdfWeight[6])
                self.h_nweightedeventspassfidselection_pdfweight7.Fill(0.5,event.LHEPdfWeight[7])
                self.h_nweightedeventspassfidselection_pdfweight8.Fill(0.5,event.LHEPdfWeight[8])
                self.h_nweightedeventspassfidselection_pdfweight9.Fill(0.5,event.LHEPdfWeight[9])
                self.h_nweightedeventspassfidselection_pdfweight10.Fill(0.5,event.LHEPdfWeight[10])
                self.h_nweightedeventspassfidselection_pdfweight11.Fill(0.5,event.LHEPdfWeight[11])
                self.h_nweightedeventspassfidselection_pdfweight12.Fill(0.5,event.LHEPdfWeight[12])
                self.h_nweightedeventspassfidselection_pdfweight13.Fill(0.5,event.LHEPdfWeight[13])
                self.h_nweightedeventspassfidselection_pdfweight14.Fill(0.5,event.LHEPdfWeight[14])
                self.h_nweightedeventspassfidselection_pdfweight15.Fill(0.5,event.LHEPdfWeight[15])
                self.h_nweightedeventspassfidselection_pdfweight16.Fill(0.5,event.LHEPdfWeight[16])
                self.h_nweightedeventspassfidselection_pdfweight17.Fill(0.5,event.LHEPdfWeight[17])
                self.h_nweightedeventspassfidselection_pdfweight18.Fill(0.5,event.LHEPdfWeight[18])
                self.h_nweightedeventspassfidselection_pdfweight19.Fill(0.5,event.LHEPdfWeight[19])
                self.h_nweightedeventspassfidselection_pdfweight20.Fill(0.5,event.LHEPdfWeight[20])
                self.h_nweightedeventspassfidselection_pdfweight21.Fill(0.5,event.LHEPdfWeight[21])
                self.h_nweightedeventspassfidselection_pdfweight22.Fill(0.5,event.LHEPdfWeight[22])
                self.h_nweightedeventspassfidselection_pdfweight23.Fill(0.5,event.LHEPdfWeight[23])
                self.h_nweightedeventspassfidselection_pdfweight24.Fill(0.5,event.LHEPdfWeight[24])
                self.h_nweightedeventspassfidselection_pdfweight25.Fill(0.5,event.LHEPdfWeight[25])
                self.h_nweightedeventspassfidselection_pdfweight26.Fill(0.5,event.LHEPdfWeight[26])
                self.h_nweightedeventspassfidselection_pdfweight27.Fill(0.5,event.LHEPdfWeight[27])
                self.h_nweightedeventspassfidselection_pdfweight28.Fill(0.5,event.LHEPdfWeight[28])
                self.h_nweightedeventspassfidselection_pdfweight29.Fill(0.5,event.LHEPdfWeight[29])
                self.h_nweightedeventspassfidselection_pdfweight30.Fill(0.5,event.LHEPdfWeight[30])
                self.h_nweightedeventspassfidselection_pdfweight31.Fill(0.5,event.LHEPdfWeight[31])
                self.h_nweightedeventspassfidselection_pdfweight32.Fill(0.5,event.LHEPdfWeight[32])
                self.h_nweightedeventspassfidselection_pdfweight33.Fill(0.5,event.LHEPdfWeight[33])
                self.h_nweightedeventspassfidselection_pdfweight34.Fill(0.5,event.LHEPdfWeight[34])
                self.h_nweightedeventspassfidselection_pdfweight35.Fill(0.5,event.LHEPdfWeight[35])
                self.h_nweightedeventspassfidselection_pdfweight36.Fill(0.5,event.LHEPdfWeight[36])
                self.h_nweightedeventspassfidselection_pdfweight37.Fill(0.5,event.LHEPdfWeight[37])
                self.h_nweightedeventspassfidselection_pdfweight38.Fill(0.5,event.LHEPdfWeight[38])
                self.h_nweightedeventspassfidselection_pdfweight39.Fill(0.5,event.LHEPdfWeight[39])
                self.h_nweightedeventspassfidselection_pdfweight40.Fill(0.5,event.LHEPdfWeight[40])
                self.h_nweightedeventspassfidselection_pdfweight41.Fill(0.5,event.LHEPdfWeight[41])
                self.h_nweightedeventspassfidselection_pdfweight42.Fill(0.5,event.LHEPdfWeight[42])
                self.h_nweightedeventspassfidselection_pdfweight43.Fill(0.5,event.LHEPdfWeight[43])
                self.h_nweightedeventspassfidselection_pdfweight44.Fill(0.5,event.LHEPdfWeight[44])
                self.h_nweightedeventspassfidselection_pdfweight45.Fill(0.5,event.LHEPdfWeight[45])
                self.h_nweightedeventspassfidselection_pdfweight46.Fill(0.5,event.LHEPdfWeight[46])
                self.h_nweightedeventspassfidselection_pdfweight47.Fill(0.5,event.LHEPdfWeight[47])
                self.h_nweightedeventspassfidselection_pdfweight48.Fill(0.5,event.LHEPdfWeight[48])
                self.h_nweightedeventspassfidselection_pdfweight49.Fill(0.5,event.LHEPdfWeight[49])
                self.h_nweightedeventspassfidselection_pdfweight50.Fill(0.5,event.LHEPdfWeight[50])
                self.h_nweightedeventspassfidselection_pdfweight51.Fill(0.5,event.LHEPdfWeight[51])
                self.h_nweightedeventspassfidselection_pdfweight52.Fill(0.5,event.LHEPdfWeight[52])
                self.h_nweightedeventspassfidselection_pdfweight53.Fill(0.5,event.LHEPdfWeight[53])
                self.h_nweightedeventspassfidselection_pdfweight54.Fill(0.5,event.LHEPdfWeight[54])
                self.h_nweightedeventspassfidselection_pdfweight55.Fill(0.5,event.LHEPdfWeight[55])
                self.h_nweightedeventspassfidselection_pdfweight56.Fill(0.5,event.LHEPdfWeight[56])
                self.h_nweightedeventspassfidselection_pdfweight57.Fill(0.5,event.LHEPdfWeight[57])
                self.h_nweightedeventspassfidselection_pdfweight58.Fill(0.5,event.LHEPdfWeight[58])
                self.h_nweightedeventspassfidselection_pdfweight59.Fill(0.5,event.LHEPdfWeight[59])
                self.h_nweightedeventspassfidselection_pdfweight60.Fill(0.5,event.LHEPdfWeight[60])
                self.h_nweightedeventspassfidselection_pdfweight61.Fill(0.5,event.LHEPdfWeight[61])
                self.h_nweightedeventspassfidselection_pdfweight62.Fill(0.5,event.LHEPdfWeight[62])
                self.h_nweightedeventspassfidselection_pdfweight63.Fill(0.5,event.LHEPdfWeight[63])
                self.h_nweightedeventspassfidselection_pdfweight64.Fill(0.5,event.LHEPdfWeight[64])
                self.h_nweightedeventspassfidselection_pdfweight65.Fill(0.5,event.LHEPdfWeight[65])
                self.h_nweightedeventspassfidselection_pdfweight66.Fill(0.5,event.LHEPdfWeight[66])
                self.h_nweightedeventspassfidselection_pdfweight67.Fill(0.5,event.LHEPdfWeight[67])
                self.h_nweightedeventspassfidselection_pdfweight68.Fill(0.5,event.LHEPdfWeight[68])
                self.h_nweightedeventspassfidselection_pdfweight69.Fill(0.5,event.LHEPdfWeight[69])
                self.h_nweightedeventspassfidselection_pdfweight70.Fill(0.5,event.LHEPdfWeight[70])
                self.h_nweightedeventspassfidselection_pdfweight71.Fill(0.5,event.LHEPdfWeight[71])
                self.h_nweightedeventspassfidselection_pdfweight72.Fill(0.5,event.LHEPdfWeight[72])
                self.h_nweightedeventspassfidselection_pdfweight73.Fill(0.5,event.LHEPdfWeight[73])
                self.h_nweightedeventspassfidselection_pdfweight74.Fill(0.5,event.LHEPdfWeight[74])
                self.h_nweightedeventspassfidselection_pdfweight75.Fill(0.5,event.LHEPdfWeight[75])
                self.h_nweightedeventspassfidselection_pdfweight76.Fill(0.5,event.LHEPdfWeight[76])
                self.h_nweightedeventspassfidselection_pdfweight77.Fill(0.5,event.LHEPdfWeight[77])
                self.h_nweightedeventspassfidselection_pdfweight78.Fill(0.5,event.LHEPdfWeight[78])
                self.h_nweightedeventspassfidselection_pdfweight79.Fill(0.5,event.LHEPdfWeight[79])
                self.h_nweightedeventspassfidselection_pdfweight80.Fill(0.5,event.LHEPdfWeight[80])
                self.h_nweightedeventspassfidselection_pdfweight81.Fill(0.5,event.LHEPdfWeight[81])
                self.h_nweightedeventspassfidselection_pdfweight82.Fill(0.5,event.LHEPdfWeight[82])
                self.h_nweightedeventspassfidselection_pdfweight83.Fill(0.5,event.LHEPdfWeight[83])
                self.h_nweightedeventspassfidselection_pdfweight84.Fill(0.5,event.LHEPdfWeight[84])
                self.h_nweightedeventspassfidselection_pdfweight85.Fill(0.5,event.LHEPdfWeight[85])
                self.h_nweightedeventspassfidselection_pdfweight86.Fill(0.5,event.LHEPdfWeight[86])
                self.h_nweightedeventspassfidselection_pdfweight87.Fill(0.5,event.LHEPdfWeight[87])
                self.h_nweightedeventspassfidselection_pdfweight88.Fill(0.5,event.LHEPdfWeight[88])
                self.h_nweightedeventspassfidselection_pdfweight89.Fill(0.5,event.LHEPdfWeight[89])
                self.h_nweightedeventspassfidselection_pdfweight90.Fill(0.5,event.LHEPdfWeight[90])
                self.h_nweightedeventspassfidselection_pdfweight91.Fill(0.5,event.LHEPdfWeight[91])
                self.h_nweightedeventspassfidselection_pdfweight92.Fill(0.5,event.LHEPdfWeight[92])
                self.h_nweightedeventspassfidselection_pdfweight93.Fill(0.5,event.LHEPdfWeight[93])
                self.h_nweightedeventspassfidselection_pdfweight94.Fill(0.5,event.LHEPdfWeight[94])
                self.h_nweightedeventspassfidselection_pdfweight95.Fill(0.5,event.LHEPdfWeight[95])
                self.h_nweightedeventspassfidselection_pdfweight96.Fill(0.5,event.LHEPdfWeight[96])
                self.h_nweightedeventspassfidselection_pdfweight97.Fill(0.5,event.LHEPdfWeight[97])
                self.h_nweightedeventspassfidselection_pdfweight98.Fill(0.5,event.LHEPdfWeight[98])
                self.h_nweightedeventspassfidselection_pdfweight99.Fill(0.5,event.LHEPdfWeight[99])
                self.h_nweightedeventspassfidselection_pdfweight100.Fill(0.5,event.LHEPdfWeight[100])
                self.h_nweightedeventspassfidselection_pdfweight101.Fill(0.5,event.LHEPdfWeight[101])
                self.h_nweightedeventspassfidselection_pdfweight102.Fill(0.5,event.LHEPdfWeight[102])
            else:
                self.h_nweightedeventspassfidselection.Fill(0.5,-1)
                self.h_nweightedeventspassfidselection_qcdscaleweight0.Fill(0.5,-event.LHEScaleWeight[0])
                self.h_nweightedeventspassfidselection_qcdscaleweight1.Fill(0.5,-event.LHEScaleWeight[1])
                self.h_nweightedeventspassfidselection_qcdscaleweight2.Fill(0.5,-event.LHEScaleWeight[2])
                self.h_nweightedeventspassfidselection_qcdscaleweight3.Fill(0.5,-event.LHEScaleWeight[3])
                self.h_nweightedeventspassfidselection_qcdscaleweight4.Fill(0.5,-event.LHEScaleWeight[4])
                self.h_nweightedeventspassfidselection_qcdscaleweight5.Fill(0.5,-event.LHEScaleWeight[5])
                self.h_nweightedeventspassfidselection_qcdscaleweight6.Fill(0.5,-event.LHEScaleWeight[6])
                self.h_nweightedeventspassfidselection_qcdscaleweight7.Fill(0.5,-event.LHEScaleWeight[7])
                self.h_nweightedeventspassfidselection_pdfweight1.Fill(0.5,-event.LHEPdfWeight[1])
                self.h_nweightedeventspassfidselection_pdfweight2.Fill(0.5,-event.LHEPdfWeight[2])
                self.h_nweightedeventspassfidselection_pdfweight3.Fill(0.5,-event.LHEPdfWeight[3])
                self.h_nweightedeventspassfidselection_pdfweight4.Fill(0.5,-event.LHEPdfWeight[4])
                self.h_nweightedeventspassfidselection_pdfweight5.Fill(0.5,-event.LHEPdfWeight[5])
                self.h_nweightedeventspassfidselection_pdfweight6.Fill(0.5,-event.LHEPdfWeight[6])
                self.h_nweightedeventspassfidselection_pdfweight7.Fill(0.5,-event.LHEPdfWeight[7])
                self.h_nweightedeventspassfidselection_pdfweight8.Fill(0.5,-event.LHEPdfWeight[8])
                self.h_nweightedeventspassfidselection_pdfweight9.Fill(0.5,-event.LHEPdfWeight[9])
                self.h_nweightedeventspassfidselection_pdfweight10.Fill(0.5,-event.LHEPdfWeight[10])
                self.h_nweightedeventspassfidselection_pdfweight11.Fill(0.5,-event.LHEPdfWeight[11])
                self.h_nweightedeventspassfidselection_pdfweight12.Fill(0.5,-event.LHEPdfWeight[12])
                self.h_nweightedeventspassfidselection_pdfweight13.Fill(0.5,-event.LHEPdfWeight[13])
                self.h_nweightedeventspassfidselection_pdfweight14.Fill(0.5,-event.LHEPdfWeight[14])
                self.h_nweightedeventspassfidselection_pdfweight15.Fill(0.5,-event.LHEPdfWeight[15])
                self.h_nweightedeventspassfidselection_pdfweight16.Fill(0.5,-event.LHEPdfWeight[16])
                self.h_nweightedeventspassfidselection_pdfweight17.Fill(0.5,-event.LHEPdfWeight[17])
                self.h_nweightedeventspassfidselection_pdfweight18.Fill(0.5,-event.LHEPdfWeight[18])
                self.h_nweightedeventspassfidselection_pdfweight19.Fill(0.5,-event.LHEPdfWeight[19])
                self.h_nweightedeventspassfidselection_pdfweight20.Fill(0.5,-event.LHEPdfWeight[20])
                self.h_nweightedeventspassfidselection_pdfweight21.Fill(0.5,-event.LHEPdfWeight[21])
                self.h_nweightedeventspassfidselection_pdfweight22.Fill(0.5,-event.LHEPdfWeight[22])
                self.h_nweightedeventspassfidselection_pdfweight23.Fill(0.5,-event.LHEPdfWeight[23])
                self.h_nweightedeventspassfidselection_pdfweight24.Fill(0.5,-event.LHEPdfWeight[24])
                self.h_nweightedeventspassfidselection_pdfweight25.Fill(0.5,-event.LHEPdfWeight[25])
                self.h_nweightedeventspassfidselection_pdfweight26.Fill(0.5,-event.LHEPdfWeight[26])
                self.h_nweightedeventspassfidselection_pdfweight27.Fill(0.5,-event.LHEPdfWeight[27])
                self.h_nweightedeventspassfidselection_pdfweight28.Fill(0.5,-event.LHEPdfWeight[28])
                self.h_nweightedeventspassfidselection_pdfweight29.Fill(0.5,-event.LHEPdfWeight[29])
                self.h_nweightedeventspassfidselection_pdfweight30.Fill(0.5,-event.LHEPdfWeight[30])
                self.h_nweightedeventspassfidselection_pdfweight31.Fill(0.5,-event.LHEPdfWeight[31])
                self.h_nweightedeventspassfidselection_pdfweight32.Fill(0.5,-event.LHEPdfWeight[32])
                self.h_nweightedeventspassfidselection_pdfweight33.Fill(0.5,-event.LHEPdfWeight[33])
                self.h_nweightedeventspassfidselection_pdfweight34.Fill(0.5,-event.LHEPdfWeight[34])
                self.h_nweightedeventspassfidselection_pdfweight35.Fill(0.5,-event.LHEPdfWeight[35])
                self.h_nweightedeventspassfidselection_pdfweight36.Fill(0.5,-event.LHEPdfWeight[36])
                self.h_nweightedeventspassfidselection_pdfweight37.Fill(0.5,-event.LHEPdfWeight[37])
                self.h_nweightedeventspassfidselection_pdfweight38.Fill(0.5,-event.LHEPdfWeight[38])
                self.h_nweightedeventspassfidselection_pdfweight39.Fill(0.5,-event.LHEPdfWeight[39])
                self.h_nweightedeventspassfidselection_pdfweight40.Fill(0.5,-event.LHEPdfWeight[40])
                self.h_nweightedeventspassfidselection_pdfweight41.Fill(0.5,-event.LHEPdfWeight[41])
                self.h_nweightedeventspassfidselection_pdfweight42.Fill(0.5,-event.LHEPdfWeight[42])
                self.h_nweightedeventspassfidselection_pdfweight43.Fill(0.5,-event.LHEPdfWeight[43])
                self.h_nweightedeventspassfidselection_pdfweight44.Fill(0.5,-event.LHEPdfWeight[44])
                self.h_nweightedeventspassfidselection_pdfweight45.Fill(0.5,-event.LHEPdfWeight[45])
                self.h_nweightedeventspassfidselection_pdfweight46.Fill(0.5,-event.LHEPdfWeight[46])
                self.h_nweightedeventspassfidselection_pdfweight47.Fill(0.5,-event.LHEPdfWeight[47])
                self.h_nweightedeventspassfidselection_pdfweight48.Fill(0.5,-event.LHEPdfWeight[48])
                self.h_nweightedeventspassfidselection_pdfweight49.Fill(0.5,-event.LHEPdfWeight[49])
                self.h_nweightedeventspassfidselection_pdfweight50.Fill(0.5,-event.LHEPdfWeight[50])
                self.h_nweightedeventspassfidselection_pdfweight51.Fill(0.5,-event.LHEPdfWeight[51])
                self.h_nweightedeventspassfidselection_pdfweight52.Fill(0.5,-event.LHEPdfWeight[52])
                self.h_nweightedeventspassfidselection_pdfweight53.Fill(0.5,-event.LHEPdfWeight[53])
                self.h_nweightedeventspassfidselection_pdfweight54.Fill(0.5,-event.LHEPdfWeight[54])
                self.h_nweightedeventspassfidselection_pdfweight55.Fill(0.5,-event.LHEPdfWeight[55])
                self.h_nweightedeventspassfidselection_pdfweight56.Fill(0.5,-event.LHEPdfWeight[56])
                self.h_nweightedeventspassfidselection_pdfweight57.Fill(0.5,-event.LHEPdfWeight[57])
                self.h_nweightedeventspassfidselection_pdfweight58.Fill(0.5,-event.LHEPdfWeight[58])
                self.h_nweightedeventspassfidselection_pdfweight59.Fill(0.5,-event.LHEPdfWeight[59])
                self.h_nweightedeventspassfidselection_pdfweight60.Fill(0.5,-event.LHEPdfWeight[60])
                self.h_nweightedeventspassfidselection_pdfweight61.Fill(0.5,-event.LHEPdfWeight[61])
                self.h_nweightedeventspassfidselection_pdfweight62.Fill(0.5,-event.LHEPdfWeight[62])
                self.h_nweightedeventspassfidselection_pdfweight63.Fill(0.5,-event.LHEPdfWeight[63])
                self.h_nweightedeventspassfidselection_pdfweight64.Fill(0.5,-event.LHEPdfWeight[64])
                self.h_nweightedeventspassfidselection_pdfweight65.Fill(0.5,-event.LHEPdfWeight[65])
                self.h_nweightedeventspassfidselection_pdfweight66.Fill(0.5,-event.LHEPdfWeight[66])
                self.h_nweightedeventspassfidselection_pdfweight67.Fill(0.5,-event.LHEPdfWeight[67])
                self.h_nweightedeventspassfidselection_pdfweight68.Fill(0.5,-event.LHEPdfWeight[68])
                self.h_nweightedeventspassfidselection_pdfweight69.Fill(0.5,-event.LHEPdfWeight[69])
                self.h_nweightedeventspassfidselection_pdfweight70.Fill(0.5,-event.LHEPdfWeight[70])
                self.h_nweightedeventspassfidselection_pdfweight71.Fill(0.5,-event.LHEPdfWeight[71])
                self.h_nweightedeventspassfidselection_pdfweight72.Fill(0.5,-event.LHEPdfWeight[72])
                self.h_nweightedeventspassfidselection_pdfweight73.Fill(0.5,-event.LHEPdfWeight[73])
                self.h_nweightedeventspassfidselection_pdfweight74.Fill(0.5,-event.LHEPdfWeight[74])
                self.h_nweightedeventspassfidselection_pdfweight75.Fill(0.5,-event.LHEPdfWeight[75])
                self.h_nweightedeventspassfidselection_pdfweight76.Fill(0.5,-event.LHEPdfWeight[76])
                self.h_nweightedeventspassfidselection_pdfweight77.Fill(0.5,-event.LHEPdfWeight[77])
                self.h_nweightedeventspassfidselection_pdfweight78.Fill(0.5,-event.LHEPdfWeight[78])
                self.h_nweightedeventspassfidselection_pdfweight79.Fill(0.5,-event.LHEPdfWeight[79])
                self.h_nweightedeventspassfidselection_pdfweight80.Fill(0.5,-event.LHEPdfWeight[80])
                self.h_nweightedeventspassfidselection_pdfweight81.Fill(0.5,-event.LHEPdfWeight[81])
                self.h_nweightedeventspassfidselection_pdfweight82.Fill(0.5,-event.LHEPdfWeight[82])
                self.h_nweightedeventspassfidselection_pdfweight83.Fill(0.5,-event.LHEPdfWeight[83])
                self.h_nweightedeventspassfidselection_pdfweight84.Fill(0.5,-event.LHEPdfWeight[84])
                self.h_nweightedeventspassfidselection_pdfweight85.Fill(0.5,-event.LHEPdfWeight[85])
                self.h_nweightedeventspassfidselection_pdfweight86.Fill(0.5,-event.LHEPdfWeight[86])
                self.h_nweightedeventspassfidselection_pdfweight87.Fill(0.5,-event.LHEPdfWeight[87])
                self.h_nweightedeventspassfidselection_pdfweight88.Fill(0.5,-event.LHEPdfWeight[88])
                self.h_nweightedeventspassfidselection_pdfweight89.Fill(0.5,-event.LHEPdfWeight[89])
                self.h_nweightedeventspassfidselection_pdfweight90.Fill(0.5,-event.LHEPdfWeight[90])
                self.h_nweightedeventspassfidselection_pdfweight91.Fill(0.5,-event.LHEPdfWeight[91])
                self.h_nweightedeventspassfidselection_pdfweight92.Fill(0.5,-event.LHEPdfWeight[92])
                self.h_nweightedeventspassfidselection_pdfweight93.Fill(0.5,-event.LHEPdfWeight[93])
                self.h_nweightedeventspassfidselection_pdfweight94.Fill(0.5,-event.LHEPdfWeight[94])
                self.h_nweightedeventspassfidselection_pdfweight95.Fill(0.5,-event.LHEPdfWeight[95])
                self.h_nweightedeventspassfidselection_pdfweight96.Fill(0.5,-event.LHEPdfWeight[96])
                self.h_nweightedeventspassfidselection_pdfweight97.Fill(0.5,-event.LHEPdfWeight[97])
                self.h_nweightedeventspassfidselection_pdfweight98.Fill(0.5,-event.LHEPdfWeight[98])
                self.h_nweightedeventspassfidselection_pdfweight99.Fill(0.5,-event.LHEPdfWeight[99])
                self.h_nweightedeventspassfidselection_pdfweight100.Fill(0.5,-event.LHEPdfWeight[100])
                self.h_nweightedeventspassfidselection_pdfweight101.Fill(0.5,-event.LHEPdfWeight[101])
                self.h_nweightedeventspassfidselection_pdfweight102.Fill(0.5,-event.LHEPdfWeight[102])
                  
        return True

countHistogramsFiducialModule = lambda : countHistogramsFiducialProducer() 

