import ROOT
ROOT.PyConfig.IgnoreCommandLineOptions = True

from PhysicsTools.NanoAODTools.postprocessing.framework.datamodel import Collection
from PhysicsTools.NanoAODTools.postprocessing.framework.eventloop import Module

from PhysicsTools.NanoAODTools.postprocessing.tools import deltaR

class countHistogramsLHEAndGenSelectionsProducer(Module):
    def __init__(self):
        pass
    def beginJob(self):
        pass
    def endJob(self):
        pass
    def beginFile(self, inputFile, outputFile, inputTree, wrappedOutputTree):
        self.h_nweightedeventspassgenselection=ROOT.TH1D('nWeightedEventsPassGenSelection',   'nWeightedEventsPassGenSelection',   1, 0, 1)
        self.h_nweightedeventspasslheselection=ROOT.TH1D('nWeightedEventsPassLHESelection',   'nWeightedEventsPassLHESelection',   1, 0, 1)
        self.h_nweightedeventspasslheandgenselection=ROOT.TH1D('nWeightedEventsPassLHEAndGenSelection',   'nWeightedEventsPassLHEAndGenSelection',   1, 0, 1)

        self.h_nweightedeventspassgenselection_qcdscaleweight0=ROOT.TH1D('nWeightedEventsPassGenSelection_QCDScaleWeight0',   'nWeightedEventsPassGenSelection_QCDScaleWeight0',   1, 0, 1)
        self.h_nweightedeventspassgenselection_qcdscaleweight1=ROOT.TH1D('nWeightedEventsPassGenSelection_QCDScaleWeight1',   'nWeightedEventsPassGenSelection_QCDScaleWeight1',   1, 0, 1)
        self.h_nweightedeventspassgenselection_qcdscaleweight2=ROOT.TH1D('nWeightedEventsPassGenSelection_QCDScaleWeight2',   'nWeightedEventsPassGenSelection_QCDScaleWeight2',   1, 0, 1)
        self.h_nweightedeventspassgenselection_qcdscaleweight3=ROOT.TH1D('nWeightedEventsPassGenSelection_QCDScaleWeight3',   'nWeightedEventsPassGenSelection_QCDScaleWeight3',   1, 0, 1)
        self.h_nweightedeventspassgenselection_qcdscaleweight4=ROOT.TH1D('nWeightedEventsPassGenSelection_QCDScaleWeight4',   'nWeightedEventsPassGenSelection_QCDScaleWeight4',   1, 0, 1)
        self.h_nweightedeventspassgenselection_qcdscaleweight5=ROOT.TH1D('nWeightedEventsPassGenSelection_QCDScaleWeight5',   'nWeightedEventsPassGenSelection_QCDScaleWeight5',   1, 0, 1)
        self.h_nweightedeventspassgenselection_qcdscaleweight6=ROOT.TH1D('nWeightedEventsPassGenSelection_QCDScaleWeight6',   'nWeightedEventsPassGenSelection_QCDScaleWeight6',   1, 0, 1)
        self.h_nweightedeventspassgenselection_qcdscaleweight7=ROOT.TH1D('nWeightedEventsPassGenSelection_QCDScaleWeight7',   'nWeightedEventsPassGenSelection_QCDScaleWeight7',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight1=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight1',   'nWeightedEventsPassGenSelection_PDFWeight1',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight2=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight2',   'nWeightedEventsPassGenSelection_PDFWeight2',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight3=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight3',   'nWeightedEventsPassGenSelection_PDFWeight3',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight4=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight4',   'nWeightedEventsPassGenSelection_PDFWeight4',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight5=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight5',   'nWeightedEventsPassGenSelection_PDFWeight5',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight6=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight6',   'nWeightedEventsPassGenSelection_PDFWeight6',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight7=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight7',   'nWeightedEventsPassGenSelection_PDFWeight7',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight8=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight8',   'nWeightedEventsPassGenSelection_PDFWeight8',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight9=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight9',   'nWeightedEventsPassGenSelection_PDFWeight9',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight10=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight10',   'nWeightedEventsPassGenSelection_PDFWeight10',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight11=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight11',   'nWeightedEventsPassGenSelection_PDFWeight11',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight12=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight12',   'nWeightedEventsPassGenSelection_PDFWeight12',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight13=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight13',   'nWeightedEventsPassGenSelection_PDFWeight13',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight14=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight14',   'nWeightedEventsPassGenSelection_PDFWeight14',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight15=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight15',   'nWeightedEventsPassGenSelection_PDFWeight15',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight16=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight16',   'nWeightedEventsPassGenSelection_PDFWeight16',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight17=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight17',   'nWeightedEventsPassGenSelection_PDFWeight17',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight18=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight18',   'nWeightedEventsPassGenSelection_PDFWeight18',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight19=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight19',   'nWeightedEventsPassGenSelection_PDFWeight19',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight20=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight20',   'nWeightedEventsPassGenSelection_PDFWeight20',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight21=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight21',   'nWeightedEventsPassGenSelection_PDFWeight21',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight22=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight22',   'nWeightedEventsPassGenSelection_PDFWeight22',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight23=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight23',   'nWeightedEventsPassGenSelection_PDFWeight23',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight24=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight24',   'nWeightedEventsPassGenSelection_PDFWeight24',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight25=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight25',   'nWeightedEventsPassGenSelection_PDFWeight25',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight26=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight26',   'nWeightedEventsPassGenSelection_PDFWeight26',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight27=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight27',   'nWeightedEventsPassGenSelection_PDFWeight27',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight28=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight28',   'nWeightedEventsPassGenSelection_PDFWeight28',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight29=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight29',   'nWeightedEventsPassGenSelection_PDFWeight29',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight30=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight30',   'nWeightedEventsPassGenSelection_PDFWeight30',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight31=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight31',   'nWeightedEventsPassGenSelection_PDFWeight31',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight32=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight32',   'nWeightedEventsPassGenSelection_PDFWeight32',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight33=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight33',   'nWeightedEventsPassGenSelection_PDFWeight33',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight34=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight34',   'nWeightedEventsPassGenSelection_PDFWeight34',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight35=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight35',   'nWeightedEventsPassGenSelection_PDFWeight35',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight36=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight36',   'nWeightedEventsPassGenSelection_PDFWeight36',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight37=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight37',   'nWeightedEventsPassGenSelection_PDFWeight37',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight38=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight38',   'nWeightedEventsPassGenSelection_PDFWeight38',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight39=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight39',   'nWeightedEventsPassGenSelection_PDFWeight39',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight40=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight40',   'nWeightedEventsPassGenSelection_PDFWeight40',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight41=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight41',   'nWeightedEventsPassGenSelection_PDFWeight41',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight42=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight42',   'nWeightedEventsPassGenSelection_PDFWeight42',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight43=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight43',   'nWeightedEventsPassGenSelection_PDFWeight43',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight44=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight44',   'nWeightedEventsPassGenSelection_PDFWeight44',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight45=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight45',   'nWeightedEventsPassGenSelection_PDFWeight45',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight46=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight46',   'nWeightedEventsPassGenSelection_PDFWeight46',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight47=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight47',   'nWeightedEventsPassGenSelection_PDFWeight47',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight48=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight48',   'nWeightedEventsPassGenSelection_PDFWeight48',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight49=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight49',   'nWeightedEventsPassGenSelection_PDFWeight49',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight50=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight50',   'nWeightedEventsPassGenSelection_PDFWeight50',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight51=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight51',   'nWeightedEventsPassGenSelection_PDFWeight51',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight52=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight52',   'nWeightedEventsPassGenSelection_PDFWeight52',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight53=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight53',   'nWeightedEventsPassGenSelection_PDFWeight53',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight54=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight54',   'nWeightedEventsPassGenSelection_PDFWeight54',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight55=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight55',   'nWeightedEventsPassGenSelection_PDFWeight55',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight56=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight56',   'nWeightedEventsPassGenSelection_PDFWeight56',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight57=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight57',   'nWeightedEventsPassGenSelection_PDFWeight57',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight58=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight58',   'nWeightedEventsPassGenSelection_PDFWeight58',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight59=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight59',   'nWeightedEventsPassGenSelection_PDFWeight59',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight60=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight60',   'nWeightedEventsPassGenSelection_PDFWeight60',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight61=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight61',   'nWeightedEventsPassGenSelection_PDFWeight61',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight62=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight62',   'nWeightedEventsPassGenSelection_PDFWeight62',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight63=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight63',   'nWeightedEventsPassGenSelection_PDFWeight63',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight64=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight64',   'nWeightedEventsPassGenSelection_PDFWeight64',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight65=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight65',   'nWeightedEventsPassGenSelection_PDFWeight65',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight66=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight66',   'nWeightedEventsPassGenSelection_PDFWeight66',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight67=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight67',   'nWeightedEventsPassGenSelection_PDFWeight67',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight68=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight68',   'nWeightedEventsPassGenSelection_PDFWeight68',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight69=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight69',   'nWeightedEventsPassGenSelection_PDFWeight69',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight70=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight70',   'nWeightedEventsPassGenSelection_PDFWeight70',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight71=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight71',   'nWeightedEventsPassGenSelection_PDFWeight71',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight72=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight72',   'nWeightedEventsPassGenSelection_PDFWeight72',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight73=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight73',   'nWeightedEventsPassGenSelection_PDFWeight73',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight74=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight74',   'nWeightedEventsPassGenSelection_PDFWeight74',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight75=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight75',   'nWeightedEventsPassGenSelection_PDFWeight75',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight76=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight76',   'nWeightedEventsPassGenSelection_PDFWeight76',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight77=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight77',   'nWeightedEventsPassGenSelection_PDFWeight77',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight78=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight78',   'nWeightedEventsPassGenSelection_PDFWeight78',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight79=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight79',   'nWeightedEventsPassGenSelection_PDFWeight79',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight80=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight80',   'nWeightedEventsPassGenSelection_PDFWeight80',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight81=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight81',   'nWeightedEventsPassGenSelection_PDFWeight81',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight82=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight82',   'nWeightedEventsPassGenSelection_PDFWeight82',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight83=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight83',   'nWeightedEventsPassGenSelection_PDFWeight83',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight84=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight84',   'nWeightedEventsPassGenSelection_PDFWeight84',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight85=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight85',   'nWeightedEventsPassGenSelection_PDFWeight85',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight86=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight86',   'nWeightedEventsPassGenSelection_PDFWeight86',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight87=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight87',   'nWeightedEventsPassGenSelection_PDFWeight87',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight88=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight88',   'nWeightedEventsPassGenSelection_PDFWeight88',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight89=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight89',   'nWeightedEventsPassGenSelection_PDFWeight89',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight90=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight90',   'nWeightedEventsPassGenSelection_PDFWeight90',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight91=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight91',   'nWeightedEventsPassGenSelection_PDFWeight91',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight92=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight92',   'nWeightedEventsPassGenSelection_PDFWeight92',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight93=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight93',   'nWeightedEventsPassGenSelection_PDFWeight93',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight94=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight94',   'nWeightedEventsPassGenSelection_PDFWeight94',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight95=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight95',   'nWeightedEventsPassGenSelection_PDFWeight95',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight96=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight96',   'nWeightedEventsPassGenSelection_PDFWeight96',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight97=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight97',   'nWeightedEventsPassGenSelection_PDFWeight97',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight98=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight98',   'nWeightedEventsPassGenSelection_PDFWeight98',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight99=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight99',   'nWeightedEventsPassGenSelection_PDFWeight99',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight100=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight100',   'nWeightedEventsPassGenSelection_PDFWeight100',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight101=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight101',   'nWeightedEventsPassGenSelection_PDFWeight101',   1, 0, 1)
        self.h_nweightedeventspassgenselection_pdfweight102=ROOT.TH1D('nWeightedEventsPassGenSelection_PDFWeight102',   'nWeightedEventsPassGenSelection_PDFWeight102',   1, 0, 1)


    def endFile(self, inputFile, outputFile, inputTree, wrappedOutputTree):
        prevdir = ROOT.gDirectory
        outputFile.cd()
        self.h_nweightedeventspassgenselection.Write()
        self.h_nweightedeventspasslheselection.Write()
        self.h_nweightedeventspasslheandgenselection.Write()
        self.h_nweightedeventspassgenselection_qcdscaleweight0.Write()
        self.h_nweightedeventspassgenselection_qcdscaleweight1.Write()
        self.h_nweightedeventspassgenselection_qcdscaleweight2.Write()
        self.h_nweightedeventspassgenselection_qcdscaleweight3.Write()
        self.h_nweightedeventspassgenselection_qcdscaleweight4.Write()
        self.h_nweightedeventspassgenselection_qcdscaleweight5.Write()
        self.h_nweightedeventspassgenselection_qcdscaleweight6.Write()
        self.h_nweightedeventspassgenselection_qcdscaleweight7.Write()
        self.h_nweightedeventspassgenselection_pdfweight1.Write()
        self.h_nweightedeventspassgenselection_pdfweight2.Write()
        self.h_nweightedeventspassgenselection_pdfweight3.Write()
        self.h_nweightedeventspassgenselection_pdfweight4.Write()
        self.h_nweightedeventspassgenselection_pdfweight5.Write()
        self.h_nweightedeventspassgenselection_pdfweight6.Write()
        self.h_nweightedeventspassgenselection_pdfweight7.Write()
        self.h_nweightedeventspassgenselection_pdfweight8.Write()
        self.h_nweightedeventspassgenselection_pdfweight9.Write()
        self.h_nweightedeventspassgenselection_pdfweight10.Write()
        self.h_nweightedeventspassgenselection_pdfweight11.Write()
        self.h_nweightedeventspassgenselection_pdfweight12.Write()
        self.h_nweightedeventspassgenselection_pdfweight13.Write()
        self.h_nweightedeventspassgenselection_pdfweight14.Write()
        self.h_nweightedeventspassgenselection_pdfweight15.Write()
        self.h_nweightedeventspassgenselection_pdfweight16.Write()
        self.h_nweightedeventspassgenselection_pdfweight17.Write()
        self.h_nweightedeventspassgenselection_pdfweight18.Write()
        self.h_nweightedeventspassgenselection_pdfweight19.Write()
        self.h_nweightedeventspassgenselection_pdfweight20.Write()
        self.h_nweightedeventspassgenselection_pdfweight21.Write()
        self.h_nweightedeventspassgenselection_pdfweight22.Write()
        self.h_nweightedeventspassgenselection_pdfweight23.Write()
        self.h_nweightedeventspassgenselection_pdfweight24.Write()
        self.h_nweightedeventspassgenselection_pdfweight25.Write()
        self.h_nweightedeventspassgenselection_pdfweight26.Write()
        self.h_nweightedeventspassgenselection_pdfweight27.Write()
        self.h_nweightedeventspassgenselection_pdfweight28.Write()
        self.h_nweightedeventspassgenselection_pdfweight29.Write()
        self.h_nweightedeventspassgenselection_pdfweight30.Write()
        self.h_nweightedeventspassgenselection_pdfweight31.Write()
        self.h_nweightedeventspassgenselection_pdfweight32.Write()
        self.h_nweightedeventspassgenselection_pdfweight33.Write()
        self.h_nweightedeventspassgenselection_pdfweight34.Write()
        self.h_nweightedeventspassgenselection_pdfweight35.Write()
        self.h_nweightedeventspassgenselection_pdfweight36.Write()
        self.h_nweightedeventspassgenselection_pdfweight37.Write()
        self.h_nweightedeventspassgenselection_pdfweight38.Write()
        self.h_nweightedeventspassgenselection_pdfweight39.Write()
        self.h_nweightedeventspassgenselection_pdfweight40.Write()
        self.h_nweightedeventspassgenselection_pdfweight41.Write()
        self.h_nweightedeventspassgenselection_pdfweight42.Write()
        self.h_nweightedeventspassgenselection_pdfweight43.Write()
        self.h_nweightedeventspassgenselection_pdfweight44.Write()
        self.h_nweightedeventspassgenselection_pdfweight45.Write()
        self.h_nweightedeventspassgenselection_pdfweight46.Write()
        self.h_nweightedeventspassgenselection_pdfweight47.Write()
        self.h_nweightedeventspassgenselection_pdfweight48.Write()
        self.h_nweightedeventspassgenselection_pdfweight49.Write()
        self.h_nweightedeventspassgenselection_pdfweight50.Write()
        self.h_nweightedeventspassgenselection_pdfweight51.Write()
        self.h_nweightedeventspassgenselection_pdfweight52.Write()
        self.h_nweightedeventspassgenselection_pdfweight53.Write()
        self.h_nweightedeventspassgenselection_pdfweight54.Write()
        self.h_nweightedeventspassgenselection_pdfweight55.Write()
        self.h_nweightedeventspassgenselection_pdfweight56.Write()
        self.h_nweightedeventspassgenselection_pdfweight57.Write()
        self.h_nweightedeventspassgenselection_pdfweight58.Write()
        self.h_nweightedeventspassgenselection_pdfweight59.Write()
        self.h_nweightedeventspassgenselection_pdfweight60.Write()
        self.h_nweightedeventspassgenselection_pdfweight61.Write()
        self.h_nweightedeventspassgenselection_pdfweight62.Write()
        self.h_nweightedeventspassgenselection_pdfweight63.Write()
        self.h_nweightedeventspassgenselection_pdfweight64.Write()
        self.h_nweightedeventspassgenselection_pdfweight65.Write()
        self.h_nweightedeventspassgenselection_pdfweight66.Write()
        self.h_nweightedeventspassgenselection_pdfweight67.Write()
        self.h_nweightedeventspassgenselection_pdfweight68.Write()
        self.h_nweightedeventspassgenselection_pdfweight69.Write()
        self.h_nweightedeventspassgenselection_pdfweight70.Write()
        self.h_nweightedeventspassgenselection_pdfweight71.Write()
        self.h_nweightedeventspassgenselection_pdfweight72.Write()
        self.h_nweightedeventspassgenselection_pdfweight73.Write()
        self.h_nweightedeventspassgenselection_pdfweight74.Write()
        self.h_nweightedeventspassgenselection_pdfweight75.Write()
        self.h_nweightedeventspassgenselection_pdfweight76.Write()
        self.h_nweightedeventspassgenselection_pdfweight77.Write()
        self.h_nweightedeventspassgenselection_pdfweight78.Write()
        self.h_nweightedeventspassgenselection_pdfweight79.Write()
        self.h_nweightedeventspassgenselection_pdfweight80.Write()
        self.h_nweightedeventspassgenselection_pdfweight81.Write()
        self.h_nweightedeventspassgenselection_pdfweight82.Write()
        self.h_nweightedeventspassgenselection_pdfweight83.Write()
        self.h_nweightedeventspassgenselection_pdfweight84.Write()
        self.h_nweightedeventspassgenselection_pdfweight85.Write()
        self.h_nweightedeventspassgenselection_pdfweight86.Write()
        self.h_nweightedeventspassgenselection_pdfweight87.Write()
        self.h_nweightedeventspassgenselection_pdfweight88.Write()
        self.h_nweightedeventspassgenselection_pdfweight89.Write()
        self.h_nweightedeventspassgenselection_pdfweight90.Write()
        self.h_nweightedeventspassgenselection_pdfweight91.Write()
        self.h_nweightedeventspassgenselection_pdfweight92.Write()
        self.h_nweightedeventspassgenselection_pdfweight93.Write()
        self.h_nweightedeventspassgenselection_pdfweight94.Write()
        self.h_nweightedeventspassgenselection_pdfweight95.Write()
        self.h_nweightedeventspassgenselection_pdfweight96.Write()
        self.h_nweightedeventspassgenselection_pdfweight97.Write()
        self.h_nweightedeventspassgenselection_pdfweight98.Write()
        self.h_nweightedeventspassgenselection_pdfweight99.Write()
        self.h_nweightedeventspassgenselection_pdfweight100.Write()
        self.h_nweightedeventspassgenselection_pdfweight101.Write()
        self.h_nweightedeventspassgenselection_pdfweight102.Write()
        prevdir.cd()        
    def analyze(self, event):
        if True:

            genparts = Collection(event, "GenPart")
            lheparts = Collection(event, "LHEPart")
            
            isprompt_mask = (1 << 0) #isPrompt
            isdirectprompttaudecayproduct_mask = (1 << 5) #isDirectPromptTauDecayProduct                                                                                                              
            n_gen_leptons = 0
            n_gen_photons = 0
            for i in range(0,len(genparts)):

                if genparts[i].pt > 20 and genparts[i].status == 1 and (abs(genparts[i].pdgId) == 11 or abs(genparts[i].pdgId) == 13) and ((genparts[i].statusFlags & isprompt_mask == isprompt_mask) or (genparts[i].statusFlags & isdirectprompttaudecayproduct_mask == isdirectprompttaudecayproduct_mask)):
                    gen_lepton_index = i
                    n_gen_leptons +=  1
                if genparts[i].pt > 20 and genparts[i].status == 1 and genparts[i].pdgId == 22 and abs(genparts[i].eta) < 2.5 and (genparts[i].statusFlags & isprompt_mask == isprompt_mask):

                    pho_iso=0
                    for j in range(0,len(genparts)):
                        
                        if j == i:
                            continue
                        
                        if genparts[j].status != 1:
                            continue

                        if abs(genparts[j].pdgId) == 12 or abs(genparts[j].pdgId) == 14 or abs(genparts[j].pdgId) == 16:
                            continue

                        if genparts[j].pt > 20 and genparts[j].status == 1 and (abs(genparts[j].pdgId) == 11 or abs(genparts[j].pdgId) == 13) and ((genparts[j].statusFlags & isprompt_mask == isprompt_mask) or (genparts[j].statusFlags & isdirectprompttaudecayproduct_mask == isdirectprompttaudecayproduct_mask)):
                            continue

                        if deltaR(genparts[j].eta,genparts[j].phi,genparts[i].eta,genparts[i].phi) < 0.4:
                            pho_iso += genparts[j].pt

                    pho_iso /= genparts[i].pt

                    if pho_iso < 0.5:
                        gen_photon_index = i
                        n_gen_photons +=1

            if n_gen_leptons == 1 and n_gen_photons == 1 and deltaR(genparts[gen_lepton_index].eta,genparts[gen_lepton_index].phi,genparts[gen_photon_index].eta,genparts[gen_photon_index].phi) > 0.5:
                pass_gen_selection = True
            else:        
                pass_gen_selection = False

            n_lhe_photons = 0
            n_lhe_leptons = 0

            for i in range(0,len(lheparts)):
                if lheparts[i].pdgId == 22:
                    lhe_photon_index=i
                    n_lhe_photons+=1
                    
                if abs(lheparts[i].pdgId) == 11 or abs(lheparts[i].pdgId) == 13 or abs(lheparts[i].pdgId) == 15:
                    lhe_lepton_index=i
                    n_lhe_leptons+=1

            #n_lhe_photons may be 0 for POWHEG        
            assert((n_lhe_leptons == 1 and n_lhe_photons == 1) or (n_lhe_leptons == 1 and n_lhe_photons == 0))  

            if pass_gen_selection:    
                if event.Generator_weight > 0:
                    self.h_nweightedeventspassgenselection.Fill(0.5)
                    self.h_nweightedeventspassgenselection_qcdscaleweight0.Fill(0.5,event.LHEScaleWeight[0])
                    self.h_nweightedeventspassgenselection_qcdscaleweight1.Fill(0.5,event.LHEScaleWeight[1])
                    self.h_nweightedeventspassgenselection_qcdscaleweight2.Fill(0.5,event.LHEScaleWeight[2])
                    self.h_nweightedeventspassgenselection_qcdscaleweight3.Fill(0.5,event.LHEScaleWeight[3])
                    self.h_nweightedeventspassgenselection_qcdscaleweight4.Fill(0.5,event.LHEScaleWeight[4])
                    self.h_nweightedeventspassgenselection_qcdscaleweight5.Fill(0.5,event.LHEScaleWeight[5])
                    self.h_nweightedeventspassgenselection_qcdscaleweight6.Fill(0.5,event.LHEScaleWeight[6])
                    self.h_nweightedeventspassgenselection_qcdscaleweight7.Fill(0.5,event.LHEScaleWeight[7])
                    self.h_nweightedeventspassgenselection_pdfweight1.Fill(0.5,event.LHEPdfWeight[1])
                    self.h_nweightedeventspassgenselection_pdfweight2.Fill(0.5,event.LHEPdfWeight[2])
                    self.h_nweightedeventspassgenselection_pdfweight3.Fill(0.5,event.LHEPdfWeight[3])
                    self.h_nweightedeventspassgenselection_pdfweight4.Fill(0.5,event.LHEPdfWeight[4])
                    self.h_nweightedeventspassgenselection_pdfweight5.Fill(0.5,event.LHEPdfWeight[5])
                    self.h_nweightedeventspassgenselection_pdfweight6.Fill(0.5,event.LHEPdfWeight[6])
                    self.h_nweightedeventspassgenselection_pdfweight7.Fill(0.5,event.LHEPdfWeight[7])
                    self.h_nweightedeventspassgenselection_pdfweight8.Fill(0.5,event.LHEPdfWeight[8])
                    self.h_nweightedeventspassgenselection_pdfweight9.Fill(0.5,event.LHEPdfWeight[9])
                    self.h_nweightedeventspassgenselection_pdfweight10.Fill(0.5,event.LHEPdfWeight[10])
                    self.h_nweightedeventspassgenselection_pdfweight11.Fill(0.5,event.LHEPdfWeight[11])
                    self.h_nweightedeventspassgenselection_pdfweight12.Fill(0.5,event.LHEPdfWeight[12])
                    self.h_nweightedeventspassgenselection_pdfweight13.Fill(0.5,event.LHEPdfWeight[13])
                    self.h_nweightedeventspassgenselection_pdfweight14.Fill(0.5,event.LHEPdfWeight[14])
                    self.h_nweightedeventspassgenselection_pdfweight15.Fill(0.5,event.LHEPdfWeight[15])
                    self.h_nweightedeventspassgenselection_pdfweight16.Fill(0.5,event.LHEPdfWeight[16])
                    self.h_nweightedeventspassgenselection_pdfweight17.Fill(0.5,event.LHEPdfWeight[17])
                    self.h_nweightedeventspassgenselection_pdfweight18.Fill(0.5,event.LHEPdfWeight[18])
                    self.h_nweightedeventspassgenselection_pdfweight19.Fill(0.5,event.LHEPdfWeight[19])
                    self.h_nweightedeventspassgenselection_pdfweight20.Fill(0.5,event.LHEPdfWeight[20])
                    self.h_nweightedeventspassgenselection_pdfweight21.Fill(0.5,event.LHEPdfWeight[21])
                    self.h_nweightedeventspassgenselection_pdfweight22.Fill(0.5,event.LHEPdfWeight[22])
                    self.h_nweightedeventspassgenselection_pdfweight23.Fill(0.5,event.LHEPdfWeight[23])
                    self.h_nweightedeventspassgenselection_pdfweight24.Fill(0.5,event.LHEPdfWeight[24])
                    self.h_nweightedeventspassgenselection_pdfweight25.Fill(0.5,event.LHEPdfWeight[25])
                    self.h_nweightedeventspassgenselection_pdfweight26.Fill(0.5,event.LHEPdfWeight[26])
                    self.h_nweightedeventspassgenselection_pdfweight27.Fill(0.5,event.LHEPdfWeight[27])
                    self.h_nweightedeventspassgenselection_pdfweight28.Fill(0.5,event.LHEPdfWeight[28])
                    self.h_nweightedeventspassgenselection_pdfweight29.Fill(0.5,event.LHEPdfWeight[29])
                    self.h_nweightedeventspassgenselection_pdfweight30.Fill(0.5,event.LHEPdfWeight[30])
                    self.h_nweightedeventspassgenselection_pdfweight31.Fill(0.5,event.LHEPdfWeight[31])
                    self.h_nweightedeventspassgenselection_pdfweight32.Fill(0.5,event.LHEPdfWeight[32])
                    self.h_nweightedeventspassgenselection_pdfweight33.Fill(0.5,event.LHEPdfWeight[33])
                    self.h_nweightedeventspassgenselection_pdfweight34.Fill(0.5,event.LHEPdfWeight[34])
                    self.h_nweightedeventspassgenselection_pdfweight35.Fill(0.5,event.LHEPdfWeight[35])
                    self.h_nweightedeventspassgenselection_pdfweight36.Fill(0.5,event.LHEPdfWeight[36])
                    self.h_nweightedeventspassgenselection_pdfweight37.Fill(0.5,event.LHEPdfWeight[37])
                    self.h_nweightedeventspassgenselection_pdfweight38.Fill(0.5,event.LHEPdfWeight[38])
                    self.h_nweightedeventspassgenselection_pdfweight39.Fill(0.5,event.LHEPdfWeight[39])
                    self.h_nweightedeventspassgenselection_pdfweight40.Fill(0.5,event.LHEPdfWeight[40])
                    self.h_nweightedeventspassgenselection_pdfweight41.Fill(0.5,event.LHEPdfWeight[41])
                    self.h_nweightedeventspassgenselection_pdfweight42.Fill(0.5,event.LHEPdfWeight[42])
                    self.h_nweightedeventspassgenselection_pdfweight43.Fill(0.5,event.LHEPdfWeight[43])
                    self.h_nweightedeventspassgenselection_pdfweight44.Fill(0.5,event.LHEPdfWeight[44])
                    self.h_nweightedeventspassgenselection_pdfweight45.Fill(0.5,event.LHEPdfWeight[45])
                    self.h_nweightedeventspassgenselection_pdfweight46.Fill(0.5,event.LHEPdfWeight[46])
                    self.h_nweightedeventspassgenselection_pdfweight47.Fill(0.5,event.LHEPdfWeight[47])
                    self.h_nweightedeventspassgenselection_pdfweight48.Fill(0.5,event.LHEPdfWeight[48])
                    self.h_nweightedeventspassgenselection_pdfweight49.Fill(0.5,event.LHEPdfWeight[49])
                    self.h_nweightedeventspassgenselection_pdfweight50.Fill(0.5,event.LHEPdfWeight[50])
                    self.h_nweightedeventspassgenselection_pdfweight51.Fill(0.5,event.LHEPdfWeight[51])
                    self.h_nweightedeventspassgenselection_pdfweight52.Fill(0.5,event.LHEPdfWeight[52])
                    self.h_nweightedeventspassgenselection_pdfweight53.Fill(0.5,event.LHEPdfWeight[53])
                    self.h_nweightedeventspassgenselection_pdfweight54.Fill(0.5,event.LHEPdfWeight[54])
                    self.h_nweightedeventspassgenselection_pdfweight55.Fill(0.5,event.LHEPdfWeight[55])
                    self.h_nweightedeventspassgenselection_pdfweight56.Fill(0.5,event.LHEPdfWeight[56])
                    self.h_nweightedeventspassgenselection_pdfweight57.Fill(0.5,event.LHEPdfWeight[57])
                    self.h_nweightedeventspassgenselection_pdfweight58.Fill(0.5,event.LHEPdfWeight[58])
                    self.h_nweightedeventspassgenselection_pdfweight59.Fill(0.5,event.LHEPdfWeight[59])
                    self.h_nweightedeventspassgenselection_pdfweight60.Fill(0.5,event.LHEPdfWeight[60])
                    self.h_nweightedeventspassgenselection_pdfweight61.Fill(0.5,event.LHEPdfWeight[61])
                    self.h_nweightedeventspassgenselection_pdfweight62.Fill(0.5,event.LHEPdfWeight[62])
                    self.h_nweightedeventspassgenselection_pdfweight63.Fill(0.5,event.LHEPdfWeight[63])
                    self.h_nweightedeventspassgenselection_pdfweight64.Fill(0.5,event.LHEPdfWeight[64])
                    self.h_nweightedeventspassgenselection_pdfweight65.Fill(0.5,event.LHEPdfWeight[65])
                    self.h_nweightedeventspassgenselection_pdfweight66.Fill(0.5,event.LHEPdfWeight[66])
                    self.h_nweightedeventspassgenselection_pdfweight67.Fill(0.5,event.LHEPdfWeight[67])
                    self.h_nweightedeventspassgenselection_pdfweight68.Fill(0.5,event.LHEPdfWeight[68])
                    self.h_nweightedeventspassgenselection_pdfweight69.Fill(0.5,event.LHEPdfWeight[69])
                    self.h_nweightedeventspassgenselection_pdfweight70.Fill(0.5,event.LHEPdfWeight[70])
                    self.h_nweightedeventspassgenselection_pdfweight71.Fill(0.5,event.LHEPdfWeight[71])
                    self.h_nweightedeventspassgenselection_pdfweight72.Fill(0.5,event.LHEPdfWeight[72])
                    self.h_nweightedeventspassgenselection_pdfweight73.Fill(0.5,event.LHEPdfWeight[73])
                    self.h_nweightedeventspassgenselection_pdfweight74.Fill(0.5,event.LHEPdfWeight[74])
                    self.h_nweightedeventspassgenselection_pdfweight75.Fill(0.5,event.LHEPdfWeight[75])
                    self.h_nweightedeventspassgenselection_pdfweight76.Fill(0.5,event.LHEPdfWeight[76])
                    self.h_nweightedeventspassgenselection_pdfweight77.Fill(0.5,event.LHEPdfWeight[77])
                    self.h_nweightedeventspassgenselection_pdfweight78.Fill(0.5,event.LHEPdfWeight[78])
                    self.h_nweightedeventspassgenselection_pdfweight79.Fill(0.5,event.LHEPdfWeight[79])
                    self.h_nweightedeventspassgenselection_pdfweight80.Fill(0.5,event.LHEPdfWeight[80])
                    self.h_nweightedeventspassgenselection_pdfweight81.Fill(0.5,event.LHEPdfWeight[81])
                    self.h_nweightedeventspassgenselection_pdfweight82.Fill(0.5,event.LHEPdfWeight[82])
                    self.h_nweightedeventspassgenselection_pdfweight83.Fill(0.5,event.LHEPdfWeight[83])
                    self.h_nweightedeventspassgenselection_pdfweight84.Fill(0.5,event.LHEPdfWeight[84])
                    self.h_nweightedeventspassgenselection_pdfweight85.Fill(0.5,event.LHEPdfWeight[85])
                    self.h_nweightedeventspassgenselection_pdfweight86.Fill(0.5,event.LHEPdfWeight[86])
                    self.h_nweightedeventspassgenselection_pdfweight87.Fill(0.5,event.LHEPdfWeight[87])
                    self.h_nweightedeventspassgenselection_pdfweight88.Fill(0.5,event.LHEPdfWeight[88])
                    self.h_nweightedeventspassgenselection_pdfweight89.Fill(0.5,event.LHEPdfWeight[89])
                    self.h_nweightedeventspassgenselection_pdfweight90.Fill(0.5,event.LHEPdfWeight[90])
                    self.h_nweightedeventspassgenselection_pdfweight91.Fill(0.5,event.LHEPdfWeight[91])
                    self.h_nweightedeventspassgenselection_pdfweight92.Fill(0.5,event.LHEPdfWeight[92])
                    self.h_nweightedeventspassgenselection_pdfweight93.Fill(0.5,event.LHEPdfWeight[93])
                    self.h_nweightedeventspassgenselection_pdfweight94.Fill(0.5,event.LHEPdfWeight[94])
                    self.h_nweightedeventspassgenselection_pdfweight95.Fill(0.5,event.LHEPdfWeight[95])
                    self.h_nweightedeventspassgenselection_pdfweight96.Fill(0.5,event.LHEPdfWeight[96])
                    self.h_nweightedeventspassgenselection_pdfweight97.Fill(0.5,event.LHEPdfWeight[97])
                    self.h_nweightedeventspassgenselection_pdfweight98.Fill(0.5,event.LHEPdfWeight[98])
                    self.h_nweightedeventspassgenselection_pdfweight99.Fill(0.5,event.LHEPdfWeight[99])
                    self.h_nweightedeventspassgenselection_pdfweight100.Fill(0.5,event.LHEPdfWeight[100])
                    self.h_nweightedeventspassgenselection_pdfweight101.Fill(0.5,event.LHEPdfWeight[101])
                    self.h_nweightedeventspassgenselection_pdfweight102.Fill(0.5,event.LHEPdfWeight[102])
                else:
                    self.h_nweightedeventspassgenselection.Fill(0.5,-1)
                    self.h_nweightedeventspassgenselection_qcdscaleweight0.Fill(0.5,-event.LHEScaleWeight[0])
                    self.h_nweightedeventspassgenselection_qcdscaleweight1.Fill(0.5,-event.LHEScaleWeight[1])
                    self.h_nweightedeventspassgenselection_qcdscaleweight2.Fill(0.5,-event.LHEScaleWeight[2])
                    self.h_nweightedeventspassgenselection_qcdscaleweight3.Fill(0.5,-event.LHEScaleWeight[3])
                    self.h_nweightedeventspassgenselection_qcdscaleweight4.Fill(0.5,-event.LHEScaleWeight[4])
                    self.h_nweightedeventspassgenselection_qcdscaleweight5.Fill(0.5,-event.LHEScaleWeight[5])
                    self.h_nweightedeventspassgenselection_qcdscaleweight6.Fill(0.5,-event.LHEScaleWeight[6])
                    self.h_nweightedeventspassgenselection_qcdscaleweight7.Fill(0.5,-event.LHEScaleWeight[7])
                    self.h_nweightedeventspassgenselection_pdfweight1.Fill(0.5,-event.LHEPdfWeight[1])
                    self.h_nweightedeventspassgenselection_pdfweight2.Fill(0.5,-event.LHEPdfWeight[2])
                    self.h_nweightedeventspassgenselection_pdfweight3.Fill(0.5,-event.LHEPdfWeight[3])
                    self.h_nweightedeventspassgenselection_pdfweight4.Fill(0.5,-event.LHEPdfWeight[4])
                    self.h_nweightedeventspassgenselection_pdfweight5.Fill(0.5,-event.LHEPdfWeight[5])
                    self.h_nweightedeventspassgenselection_pdfweight6.Fill(0.5,-event.LHEPdfWeight[6])
                    self.h_nweightedeventspassgenselection_pdfweight7.Fill(0.5,-event.LHEPdfWeight[7])
                    self.h_nweightedeventspassgenselection_pdfweight8.Fill(0.5,-event.LHEPdfWeight[8])
                    self.h_nweightedeventspassgenselection_pdfweight9.Fill(0.5,-event.LHEPdfWeight[9])
                    self.h_nweightedeventspassgenselection_pdfweight10.Fill(0.5,-event.LHEPdfWeight[10])
                    self.h_nweightedeventspassgenselection_pdfweight11.Fill(0.5,-event.LHEPdfWeight[11])
                    self.h_nweightedeventspassgenselection_pdfweight12.Fill(0.5,-event.LHEPdfWeight[12])
                    self.h_nweightedeventspassgenselection_pdfweight13.Fill(0.5,-event.LHEPdfWeight[13])
                    self.h_nweightedeventspassgenselection_pdfweight14.Fill(0.5,-event.LHEPdfWeight[14])
                    self.h_nweightedeventspassgenselection_pdfweight15.Fill(0.5,-event.LHEPdfWeight[15])
                    self.h_nweightedeventspassgenselection_pdfweight16.Fill(0.5,-event.LHEPdfWeight[16])
                    self.h_nweightedeventspassgenselection_pdfweight17.Fill(0.5,-event.LHEPdfWeight[17])
                    self.h_nweightedeventspassgenselection_pdfweight18.Fill(0.5,-event.LHEPdfWeight[18])
                    self.h_nweightedeventspassgenselection_pdfweight19.Fill(0.5,-event.LHEPdfWeight[19])
                    self.h_nweightedeventspassgenselection_pdfweight20.Fill(0.5,-event.LHEPdfWeight[20])
                    self.h_nweightedeventspassgenselection_pdfweight21.Fill(0.5,-event.LHEPdfWeight[21])
                    self.h_nweightedeventspassgenselection_pdfweight22.Fill(0.5,-event.LHEPdfWeight[22])
                    self.h_nweightedeventspassgenselection_pdfweight23.Fill(0.5,-event.LHEPdfWeight[23])
                    self.h_nweightedeventspassgenselection_pdfweight24.Fill(0.5,-event.LHEPdfWeight[24])
                    self.h_nweightedeventspassgenselection_pdfweight25.Fill(0.5,-event.LHEPdfWeight[25])
                    self.h_nweightedeventspassgenselection_pdfweight26.Fill(0.5,-event.LHEPdfWeight[26])
                    self.h_nweightedeventspassgenselection_pdfweight27.Fill(0.5,-event.LHEPdfWeight[27])
                    self.h_nweightedeventspassgenselection_pdfweight28.Fill(0.5,-event.LHEPdfWeight[28])
                    self.h_nweightedeventspassgenselection_pdfweight29.Fill(0.5,-event.LHEPdfWeight[29])
                    self.h_nweightedeventspassgenselection_pdfweight30.Fill(0.5,-event.LHEPdfWeight[30])
                    self.h_nweightedeventspassgenselection_pdfweight31.Fill(0.5,-event.LHEPdfWeight[31])
                    self.h_nweightedeventspassgenselection_pdfweight32.Fill(0.5,-event.LHEPdfWeight[32])
                    self.h_nweightedeventspassgenselection_pdfweight33.Fill(0.5,-event.LHEPdfWeight[33])
                    self.h_nweightedeventspassgenselection_pdfweight34.Fill(0.5,-event.LHEPdfWeight[34])
                    self.h_nweightedeventspassgenselection_pdfweight35.Fill(0.5,-event.LHEPdfWeight[35])
                    self.h_nweightedeventspassgenselection_pdfweight36.Fill(0.5,-event.LHEPdfWeight[36])
                    self.h_nweightedeventspassgenselection_pdfweight37.Fill(0.5,-event.LHEPdfWeight[37])
                    self.h_nweightedeventspassgenselection_pdfweight38.Fill(0.5,-event.LHEPdfWeight[38])
                    self.h_nweightedeventspassgenselection_pdfweight39.Fill(0.5,-event.LHEPdfWeight[39])
                    self.h_nweightedeventspassgenselection_pdfweight40.Fill(0.5,-event.LHEPdfWeight[40])
                    self.h_nweightedeventspassgenselection_pdfweight41.Fill(0.5,-event.LHEPdfWeight[41])
                    self.h_nweightedeventspassgenselection_pdfweight42.Fill(0.5,-event.LHEPdfWeight[42])
                    self.h_nweightedeventspassgenselection_pdfweight43.Fill(0.5,-event.LHEPdfWeight[43])
                    self.h_nweightedeventspassgenselection_pdfweight44.Fill(0.5,-event.LHEPdfWeight[44])
                    self.h_nweightedeventspassgenselection_pdfweight45.Fill(0.5,-event.LHEPdfWeight[45])
                    self.h_nweightedeventspassgenselection_pdfweight46.Fill(0.5,-event.LHEPdfWeight[46])
                    self.h_nweightedeventspassgenselection_pdfweight47.Fill(0.5,-event.LHEPdfWeight[47])
                    self.h_nweightedeventspassgenselection_pdfweight48.Fill(0.5,-event.LHEPdfWeight[48])
                    self.h_nweightedeventspassgenselection_pdfweight49.Fill(0.5,-event.LHEPdfWeight[49])
                    self.h_nweightedeventspassgenselection_pdfweight50.Fill(0.5,-event.LHEPdfWeight[50])
                    self.h_nweightedeventspassgenselection_pdfweight51.Fill(0.5,-event.LHEPdfWeight[51])
                    self.h_nweightedeventspassgenselection_pdfweight52.Fill(0.5,-event.LHEPdfWeight[52])
                    self.h_nweightedeventspassgenselection_pdfweight53.Fill(0.5,-event.LHEPdfWeight[53])
                    self.h_nweightedeventspassgenselection_pdfweight54.Fill(0.5,-event.LHEPdfWeight[54])
                    self.h_nweightedeventspassgenselection_pdfweight55.Fill(0.5,-event.LHEPdfWeight[55])
                    self.h_nweightedeventspassgenselection_pdfweight56.Fill(0.5,-event.LHEPdfWeight[56])
                    self.h_nweightedeventspassgenselection_pdfweight57.Fill(0.5,-event.LHEPdfWeight[57])
                    self.h_nweightedeventspassgenselection_pdfweight58.Fill(0.5,-event.LHEPdfWeight[58])
                    self.h_nweightedeventspassgenselection_pdfweight59.Fill(0.5,-event.LHEPdfWeight[59])
                    self.h_nweightedeventspassgenselection_pdfweight60.Fill(0.5,-event.LHEPdfWeight[60])
                    self.h_nweightedeventspassgenselection_pdfweight61.Fill(0.5,-event.LHEPdfWeight[61])
                    self.h_nweightedeventspassgenselection_pdfweight62.Fill(0.5,-event.LHEPdfWeight[62])
                    self.h_nweightedeventspassgenselection_pdfweight63.Fill(0.5,-event.LHEPdfWeight[63])
                    self.h_nweightedeventspassgenselection_pdfweight64.Fill(0.5,-event.LHEPdfWeight[64])
                    self.h_nweightedeventspassgenselection_pdfweight65.Fill(0.5,-event.LHEPdfWeight[65])
                    self.h_nweightedeventspassgenselection_pdfweight66.Fill(0.5,-event.LHEPdfWeight[66])
                    self.h_nweightedeventspassgenselection_pdfweight67.Fill(0.5,-event.LHEPdfWeight[67])
                    self.h_nweightedeventspassgenselection_pdfweight68.Fill(0.5,-event.LHEPdfWeight[68])
                    self.h_nweightedeventspassgenselection_pdfweight69.Fill(0.5,-event.LHEPdfWeight[69])
                    self.h_nweightedeventspassgenselection_pdfweight70.Fill(0.5,-event.LHEPdfWeight[70])
                    self.h_nweightedeventspassgenselection_pdfweight71.Fill(0.5,-event.LHEPdfWeight[71])
                    self.h_nweightedeventspassgenselection_pdfweight72.Fill(0.5,-event.LHEPdfWeight[72])
                    self.h_nweightedeventspassgenselection_pdfweight73.Fill(0.5,-event.LHEPdfWeight[73])
                    self.h_nweightedeventspassgenselection_pdfweight74.Fill(0.5,-event.LHEPdfWeight[74])
                    self.h_nweightedeventspassgenselection_pdfweight75.Fill(0.5,-event.LHEPdfWeight[75])
                    self.h_nweightedeventspassgenselection_pdfweight76.Fill(0.5,-event.LHEPdfWeight[76])
                    self.h_nweightedeventspassgenselection_pdfweight77.Fill(0.5,-event.LHEPdfWeight[77])
                    self.h_nweightedeventspassgenselection_pdfweight78.Fill(0.5,-event.LHEPdfWeight[78])
                    self.h_nweightedeventspassgenselection_pdfweight79.Fill(0.5,-event.LHEPdfWeight[79])
                    self.h_nweightedeventspassgenselection_pdfweight80.Fill(0.5,-event.LHEPdfWeight[80])
                    self.h_nweightedeventspassgenselection_pdfweight81.Fill(0.5,-event.LHEPdfWeight[81])
                    self.h_nweightedeventspassgenselection_pdfweight82.Fill(0.5,-event.LHEPdfWeight[82])
                    self.h_nweightedeventspassgenselection_pdfweight83.Fill(0.5,-event.LHEPdfWeight[83])
                    self.h_nweightedeventspassgenselection_pdfweight84.Fill(0.5,-event.LHEPdfWeight[84])
                    self.h_nweightedeventspassgenselection_pdfweight85.Fill(0.5,-event.LHEPdfWeight[85])
                    self.h_nweightedeventspassgenselection_pdfweight86.Fill(0.5,-event.LHEPdfWeight[86])
                    self.h_nweightedeventspassgenselection_pdfweight87.Fill(0.5,-event.LHEPdfWeight[87])
                    self.h_nweightedeventspassgenselection_pdfweight88.Fill(0.5,-event.LHEPdfWeight[88])
                    self.h_nweightedeventspassgenselection_pdfweight89.Fill(0.5,-event.LHEPdfWeight[89])
                    self.h_nweightedeventspassgenselection_pdfweight90.Fill(0.5,-event.LHEPdfWeight[90])
                    self.h_nweightedeventspassgenselection_pdfweight91.Fill(0.5,-event.LHEPdfWeight[91])
                    self.h_nweightedeventspassgenselection_pdfweight92.Fill(0.5,-event.LHEPdfWeight[92])
                    self.h_nweightedeventspassgenselection_pdfweight93.Fill(0.5,-event.LHEPdfWeight[93])
                    self.h_nweightedeventspassgenselection_pdfweight94.Fill(0.5,-event.LHEPdfWeight[94])
                    self.h_nweightedeventspassgenselection_pdfweight95.Fill(0.5,-event.LHEPdfWeight[95])
                    self.h_nweightedeventspassgenselection_pdfweight96.Fill(0.5,-event.LHEPdfWeight[96])
                    self.h_nweightedeventspassgenselection_pdfweight97.Fill(0.5,-event.LHEPdfWeight[97])
                    self.h_nweightedeventspassgenselection_pdfweight98.Fill(0.5,-event.LHEPdfWeight[98])
                    self.h_nweightedeventspassgenselection_pdfweight99.Fill(0.5,-event.LHEPdfWeight[99])
                    self.h_nweightedeventspassgenselection_pdfweight100.Fill(0.5,-event.LHEPdfWeight[100])
                    self.h_nweightedeventspassgenselection_pdfweight101.Fill(0.5,-event.LHEPdfWeight[101])
                    self.h_nweightedeventspassgenselection_pdfweight102.Fill(0.5,-event.LHEPdfWeight[102])
                  
            if n_lhe_leptons == 1 and n_lhe_photons == 1:
                if deltaR(lheparts[lhe_lepton_index].eta,lheparts[lhe_lepton_index].phi,lheparts[lhe_photon_index].eta,lheparts[lhe_photon_index].phi) > 0.1 and lheparts[lhe_lepton_index].pt > 15 and lheparts[lhe_photon_index].pt > 15 and abs(lheparts[lhe_photon_index].eta) < 2.6:
                    pass_lhe_selection = True
                else:
                    pass_lhe_selection = False

                if pass_lhe_selection:    
                    if event.Generator_weight > 0:
                        self.h_nweightedeventspasslheselection.Fill(0.5)
                    else:
                        self.h_nweightedeventspasslheselection.Fill(0.5,-1)

                if pass_lhe_selection and pass_gen_selection:        
                    if event.Generator_weight > 0:
                        self.h_nweightedeventspasslheandgenselection.Fill(0.5)
                    else:
                        self.h_nweightedeventspasslheandgenselection.Fill(0.5,-1)

        return True

countHistogramsLHEAndGenSelectionsModule = lambda : countHistogramsLHEAndGenSelectionsProducer() 

